Add /upgrade-mapblocks command
minetest/minetest pull request #10293
Opened 2020-08-15 15:11 UTC by SmallJoker

This command is designed to provide the easiest transition possible to update ancient maps.
In the future it will allow to remove support for very old maps (< 0.4.x) to get rid of the legacy code.

Removes unused code, minor code tidy.

## To do

This PR is Ready for Review.

## How to test

1) Have an old map, example: https://forum.minetest.net/viewtopic.php?f=12&t=3364
2) Ensure the log level is set to `action` or lower
3) Join the world
4) `/upgrade-mapblocks`
5) Check log output

2020-08-15 15:29 UTC, SmallJoker commented on src/map.cpp
> +			block->resetModified();
Sneaky change. This updates mapblocks automatically if they're older than what `MapBlock::serialize` supports. It should spread the load and incrementally update old maps.

Is it acceptable or shall I revert this part?

2020-08-15 15:29 UTC, SmallJoker commented on src/map.cpp
> -void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool save_after_load)
Note to reviewers: Unused argument, was always `false`.

2020-08-15 15:32 UTC, SmallJoker commented on src/server.cpp
> +	delete m_emerge;
Note to reviewers: This fixes a segfault in `deactivateFarObjects` where `EmergeManager` was required in a later stage. Leaving the world now produces warnings, but that's far better than a crash.

2020-08-15 21:01 UTC, paramat commented on builtin/game/chat.lua
> +core.register_chatcommand("upgrade-mapblocks", {
"upgrade_mapblocks" or "upgrademapblocks" for consistency with other chat commands.

2020-08-20 12:41 UTC, pyrollo commented
Wouldn't it be better to have some kind of command line utility (or argument) instead of a chat command that will be used only once in a while ?

2020-08-20 16:55 UTC, SmallJoker commented
I originally wanted to make it a startup command, but here you need to load the entire map plus node definitions and objects - after all that it results in starting an entire server anyway.

2020-08-20 17:10 UTC, pyrollo commented
Then a simple command line argument to allow such conversion. Something like `--migrate` option. So, to upgrade map blocks you would have to run once something like:
```
minetest --world XXX --upgrade_mapblocks YY
```

2021-01-04 15:40 UTC, nerzhul requested changes

2021-01-04 15:40 UTC, nerzhul commented on src/script/lua_api/l_env.cpp
> +	env->upgradeMapBlocks(version);
as i see it's done synchronously and can take ages.

I suggest to spawn a thread and do it asynchronously for non loaded blocks.

Also i suggest to implement a command line switch like we have to migrate db in order to upgrade db synchronously at startup, or a minetest.conf flag, as you like. It's clearly better than a command line from the in game admin, which will just break end user experience if playing (except if you succeed to implement it asynchronously)

2021-09-13 20:23 UTC, sfan5 commented
Superseded by `--recompress`.

2021-09-13 20:23 UTC, closed without merging