make Thread::kill() private
minetest/minetest pull request #10317
Opened 2020-08-24 09:02 UTC by semarie

The Thread kill() method isn't used outside testThreadKill unit test
and Thread destructor. It could be make private.

The testThreadKill test should be removed: it tests the kill() feature
in a way minetest doesn't use it (kill and restart a thread), specially
because some pthreads implementations on BSD will not allow to lock
again the m_start_finished_mutex which is hold when the thread is
killed.

Closes: #6065

This PR is Ready for Review.

Eventually, the `Thread::kill()` method could be merged inside `Thread::~Thread()`

2020-08-29 16:31 UTC, pyrollo commented on src/threading/thread.h
> +	 */
As this method is now private, I'm not sure this comment is still relevant. But a comment about why it as been made private could avoid any future mistake making it public again (mentioning BSD?).

2020-08-31 08:46 UTC, nerzhul commented
if we use only kill on our test, it's just a useless method. Drop it, less maintenance to do on dead called code :)

2020-08-31 13:24 UTC, pyrollo commented
It is still called by Thread destructor. I guess the code could be moved there then.

2020-09-01 06:03 UTC, nerzhul commented
i agree with you @pyrollo

2020-09-02 07:28 UTC, semarie commented
I will look to merge the kill() method inside the destructor

2020-09-06 17:15 UTC, pyrollo commented
Looks good to me but I have no BSD setup to test on.

2020-09-06 18:08 UTC, semarie commented
It should require a BSD to test.

The testThreadKill tested that a Thread could be killed and restarted safely (something not used in minetest). But it was relying on undefined behaviour for that: the fact that a random thread could unlock a mutex hold by a cancelled thread (something forbidden on BSD, but allowed with glibc on Linux).

Now that the `kill()` method is merged in the destructor, it is explicit that a Thread is killed only in the destructor: the thread couldn't be reused.

2020-09-08 14:22 UTC, nerzhul requested changes

2020-09-08 14:22 UTC, nerzhul commented on src/threading/thread.cpp
> +		m_running = false;
as you are in destructor, you can drop all asignment there because after destructor we won't read them :D

2020-09-08 15:52 UTC, semarie commented
> as you are in destructor, you can drop all asignment there because after destructor we won't read them :D

I was more concerned by concurrent access than about what can happens after destructor.

I don't know enough C++ to be sure that if the destructor is called it means really nothing has reference on it and could race with the code inside the destructor. So I was conservative.

2020-09-08 18:07 UTC, sfan5 approved these changes
Looks fine.

2020-09-09 08:40 UTC, pyrollo commented on src/threading/thread.cpp
> +		m_request_stop = false;
Same as Nerzhul told above, these assignments are useless now.

2020-09-09 08:42 UTC, pyrollo commented
Ok for me once superfluous assignments removed.

2020-09-09 11:24 UTC, semarie commented
I removed the assigments done after killing the thread, but keep the one before
(m_running = false), as in !_WIN32 case, the code will call `wait()` function,
and there is an assert on `m_running`.

2020-09-09 16:33 UTC, SmallJoker approved these changes
Works on Linux.

2020-09-10 08:35 UTC, pyrollo commented
Performing a test on (virtual) Windows before merging.

2020-09-10 10:19 UTC, merged