Disable pointing for range = -1
minetest/minetest pull request #10356
Opened 2020-08-31 12:19 UTC by appgurueu

Disables pointing for items with range = -1. Closes #10355 . Ready for Review.

## How to test

```lua
minetest.register_tool("testmod:rangetester", { description = "Range tester", range = -1 })
```

2020-09-01 06:05 UTC, nerzhul commented
why not just any value < 0 ? it will be closer to many return codes we have in UNIX calls

2020-09-01 09:06 UTC, pyrollo requested changes
Agree with nerzhul, any negative value could disable pointing (but -1 is also ok for me).

2020-09-01 09:06 UTC, pyrollo commented on src/client/game.cpp
> +			!runData.down_for_dig, camera_offset);
```suggestion
	if (d != -1)
		pointed = updatePointedThing(shootline,
				selected_def.liquids_pointable,
				!runData.btn_down_for_dig,
				camera_offset);
```
Compilation error due to `down_for_dig` not being a member of `GameRunData`
And code style

2020-09-01 11:19 UTC, HybridDog commented on src/client/game.cpp
> +		d = d == -1 ? d : 0;
Pointing should be disabled here (according to the comment), so I think this should be `d = -1;`.

2020-09-30 16:01 UTC, paramat commented
@appgurueu changes needed.

2020-10-27 17:53 UTC, appgurueu commented
I'm doubting whether this is the way to go. I would like to maintain compatibility as much as possible. If -1 was used, older clients would have max hand range, which is not intended. Modders want to use +/- 0. In order to differentiate between "allow pointing if inside [very rare use case]" and "never allow pointing" we could use the float sign bit.

2020-10-27 17:53 UTC, closed without merging