Base64: Increase performance by not using string::find
minetest/minetest pull request #10516
Opened 2020-10-18 14:25 UTC by appgurueu

Title says it all. Instead of iterating all possible characters and comparing, it uses the ASCII ranges to compare & subtract.

2020-10-19 00:25 UTC, lhofhansl commented
Clever. Did you see this as a problem in a profiler. Or just a "random" improvement? (Nothing wrong with that, just curious)

2020-10-19 09:29 UTC, appgurueu commented
> Clever. Did you see this as a problem in a profiler. Or just a "random" improvement? (Nothing wrong with that, just curious)

Random improvement, I was having a look at the code for the validation fix and noticed that it was using string::find.

2020-10-20 19:24 UTC, numberZero commented
You’re optimizing the wrong part of the function. Besides, there’s UB if the string length is not divisible by 4 as 0 (ASCII NUL, not digit zero) is passed to your function in that case.

2020-12-27 13:23 UTC, appgurueu commented
> It seems you’re optimizing the wrong part of the function. Besides, there’s UB if the string length is not divisible by 4 as 0 (ASCII NUL, not digit zero) is passed to your function in that case.

Should be addressed now.

2021-01-05 14:08 UTC, nerzhul requested changes

2021-01-05 14:08 UTC, nerzhul commented on src/util/base64.cpp
> +static const size_t nullIndex = base64_chars.find((char)0);
beltter that const, const constexpr to calculat it at compilation time

2021-10-31 19:41 UTC, rubenwardy commented
Closed as no response since action/change needed

2021-10-31 19:41 UTC, closed without merging