No damage effects on hp_max change
minetest/minetest pull request #10569
Opened 2020-10-27 16:34 UTC by appgurueu

Closes #7876

Test using the following code (**EPILEPSY WARNING**):
```lua
minetest.register_globalstep(function()
    for _, player in pairs(minetest.get_connected_players()) do
        local hp_max = math.random(1, 20)
        player:set_properties{hp_max = hp_max}
        player:set_hp(hp_max)
    end
end)
```

2020-10-27 16:37 UTC, sfan5 commented on src/network/clientpackethandler.cpp
> +		// try-catch to preserve backwards compat
should be obvious to the reader, but even if not it doesn't make sense to put this comment everywhere the try-catch idom is used
```suggestion
```

2020-10-27 16:38 UTC, sfan5 commented on src/server.cpp
> +	SendPlayerHPOrDie(playersao, reason, true);
Instead of this, the method argument should have a default value.

2020-10-27 16:38 UTC, sfan5 commented on src/server.cpp
> +	NetworkPacket pkt(TOCLIENT_HP, 2, peer_id);
it's 3 bytes now, actually

2020-10-27 16:39 UTC, sfan5 commented on src/server.cpp
> +	SendPlayerHP(peer_id, true);
a default argument value would also make this change unnecessary

2020-11-19 16:18 UTC, SmallJoker commented
That's not exactly what the issue is about:

> Yes, damage being visible in gameplay when max hp is reduced below current makes sense, it just doesn't make sense for a new player to experience that on first join (or for a new player on first join to see more hearts than they actually have).

Damage indicators are reasonable and I'd like to keep those in-game. This effect should only be ignored until after `on_joinplayer` is executed (or similar).

2020-11-19 17:31 UTC, appgurueu commented
> That's not exactly what the issue is about

It is. If modders want to preserve legacy behavior, they can do so by calling `set_hp` first.

2020-12-26 15:50 UTC, appgurueu commented
Bump

2021-05-05 15:54 UTC, sfan5 requested changes
Looks okay otherwise.

2021-05-05 15:54 UTC, sfan5 commented on src/network/clientpackethandler.cpp
> +		} catch (PacketError &e) {};
Please keep this cleanly separated and move it next to `*pkt >> hp;`

2021-12-07 16:49 UTC, closed without merging