Add new standalone file-browser in Lua
minetest/minetest pull request #10580
Opened 2020-10-31 18:29 UTC by kilbith

New standalone file-browser made in Lua, extensible to sort by file extension.

![Capture d’écran de 2020-10-31 19-25-05](https://user-images.githubusercontent.com/7883281/97786896-e7136700-1bae-11eb-94d2-b42f4ccc6dc7.png)
_Don't pay attention to the buttons colors, it's Kidscode defaults only_
The tree path is clickable by level using `hypertext`

Irrlicht file browser for comparison
![Capture d’écran de 2020-10-31 19-22-26](https://user-images.githubusercontent.com/7883281/97786949-3a85b500-1baf-11eb-8079-f63c2f453d6f.png)

2020-10-31 18:34 UTC, appgurueu commented
Beautiful like all your interfaces. Love it.

2020-10-31 20:16 UTC, paramat commented
Thanks for the feature, but please post new screenshots that do not contain and highlight 'fsck_paramat.png' files. I have removed your screenshots.

2020-10-31 20:35 UTC, MoNTE48 commented
Oh, how touchy we are. And also how we love to edit other people's messages. ^^^

2020-10-31 21:10 UTC, appgurueu requested changes

2020-10-31 21:10 UTC, appgurueu commented on builtin/mainmenu/dlg_file_browser.lua
> +local ESC = core.formspec_escape
Seeing as `ESC` is only used for textures, how about:
```lua
local function texture(filename) return core.formspec_escape(defaulttexturedir .. filename .. ".png") end
```

2020-10-31 21:10 UTC, appgurueu commented on builtin/mainmenu/dlg_file_browser.lua
> +			ESC(defaulttexturedir .. "arrow_up.png") .. ";updir;]" ..
This for instance would accordingly be `texture("arrow_up")`. This entire formspec however should IMO be a string to be formatted using `string.format`.

2020-10-31 21:10 UTC, appgurueu commented on builtin/mainmenu/dlg_file_browser.lua
> +				size = size / 1000
Filesize code can be shortened and beautified. Use something like:
```lua
local index = math.floor(math.log10(size) / 3)
local unit = ({"", "K", "M", "G", "T"})[index]
_dirs = _dirs .. string.format("%.1f", size / math.pow(10, index * 3)) .. " " .. unit .. "B,"
```

2020-10-31 21:10 UTC, appgurueu commented on builtin/mainmenu/dlg_file_browser.lua
> +local function fields_handler(this, fields)
It's usually called `self`...

2020-10-31 21:10 UTC, appgurueu commented on builtin/mainmenu/dlg_file_browser.lua
> +			return true
All these `return ... elseif`s with the newlines... Couldn't you remove the elses?

2020-10-31 21:18 UTC, kilbith commented on builtin/mainmenu/dlg_file_browser.lua
> +			local is_file = f:match("^.+(%..+)$")
I'm against using the `lfs` lib just for that

2020-10-31 21:51 UTC, sfan5 commented on builtin/mainmenu/dlg_file_browser.lua
> +			local is_file = f:match("^.+(%..+)$")
Yeah, if extra functionality is needed write a C function and expose it to Lua. We won't be adding an entire library.

2020-10-31 21:52 UTC, sfan5 commented on builtin/mainmenu/dlg_file_browser.lua
> +local function filesize(name)
There is not much wrong with this approach, though a `stat` call would be more efficient (and could also solve the folder or not issue below).

2020-11-01 09:47 UTC, appgurueu commented
A secured `lfs` would definitely be a cleaner solution than reinventing the wheel.

2020-11-01 13:18 UTC, celeron55 commented
I'm closing this PR because of the aggressive language used by kilbith.

kilbith can re-create this PR without the aggressive language if he wishes this PR to exist.

If kilbith comes back with aggressive language, I will reinstantiate his permanent ban.

2020-11-01 13:18 UTC, closed without merging

2020-11-05 18:13 UTC, lhofhansl commented
It's a bit of a shame. I like this feature, at the same time we do need aggressive language, especially when it does not contribute to the discussion. For some it might be joke, and for some it does not feel this way. I like spirited discussion as long as it is constructive.

@kilbith are you willing to file a new PR with the same code? It's certainly the most effective way to influence the project in the direction you like. I'll happily review then.

2020-11-05 18:38 UTC, kilbith commented
No I’m not willing to re-open it. I give once, not twice

2020-11-14 06:20 UTC, lhofhansl commented
¯\_(ツ)_/¯

2022-01-19 12:16 UTC, Kimapr commented on builtin/mainmenu/dlg_file_browser.lua
> +local function filesize(name)
> Reading a file just for getting it's size? Please involve `lfs` instead.

But it doesn't read the file, just opens it and seeks to the end.