Clang-format: increase column limit from 90 to 105
minetest/minetest pull request #10792
Opened 2021-01-10 10:49 UTC by Zughy

Closes #10740 

* The majority of core devs agree, celeron included
* As the previous one was 90, i.e. 10 more than the soft limit (80), and the soft limit core devs agreed one is now 95, I applied the same difference (95 + 10 = 105)

## To do

This PR is Ready for Review.

2021-01-10 19:26 UTC, Desour commented
While you are at it, would you mind fixing the indent width?

https://dev.minetest.net/Code_style_guidelines#Don.27t_let_things_get_too_large
>(Note that this column count assumes 4-space indents.)

2021-01-11 19:03 UTC, Zughy commented
@Desour I'm honestly super confused, I realise this is bigger than me https://irc.minetest.net/minetest-dev/2021-01-11#i_5772268

2021-01-21 23:26 UTC, sfan5 commented
Change the config to say `IndentWidth: 4`

2021-01-23 21:31 UTC, rubenwardy commented on .clang-format
>  AccessModifierOffset: -8
-4

2021-01-23 21:31 UTC, rubenwardy commented on .clang-format
>  AccessModifierOffset: -8
also 

ContinuationIndentWidth: 8
ConstructorInitializerIndentWidth: 8

2021-01-23 21:33 UTC, Zughy commented on .clang-format
>  AccessModifierOffset: -8
Done

2021-01-23 23:40 UTC, sfan5 commented
Now clang-format wants to realign everything that was put on multiple lines due to the column limit before.

What a shitty mess...

2021-01-23 23:56 UTC, rubenwardy commented
Great, clang-format runs differently locally to on CI

2021-01-24 00:14 UTC, sfan5 requested changes

2021-01-24 00:14 UTC, sfan5 commented on src/script/lua_api/l_modchannels.cpp
> +	lua_pop(L, 1);					// Drop methodtable
?????????????

2021-01-24 00:14 UTC, sfan5 commented on src/util/sha2.h
> +					  * contiguous array of 32 bit wide                                                 \
wtf is this

2021-01-24 00:14 UTC, sfan5 commented on src/content/mods.cpp
> +					<< "]: failed read data "
this should be two (or one?) but now it's three

2021-01-24 00:16 UTC, sfan5 commented
:-1:
Letting clang-format make hundred lines of shit changes to our codebase (some of which aren't even correct) for **no** reason is not acceptable.
Badly working linting is clearly worse than no linting at all so I suggest finally removing the cancer that is clang-format from our CI.

2021-01-24 00:16 UTC, rubenwardy commented
clang-format is broken on my computer currently, I suggest that someone else tries to run it

2021-01-24 00:19 UTC, sfan5 commented
If in the years we've had it nobody has been able to configure it to exactly match our codestyle I can only assume it is impossible.

2021-01-24 00:20 UTC, rubenwardy commented
We need to change our codestyle to be less arbitrary. For example: we use two tabs of indentation for continuation, except for statements where one is used

2021-01-24 00:21 UTC, rubenwardy commented
I think clang-format as it is is damaging and should be removed if it stays this way. But automatic formatting is a massive productivity booster because it removes the need to argue over style

2021-01-24 00:31 UTC, numberZero commented
> But automatic formatting is a massive productivity booster because it removes the need to argue over style

Then what e.g. #10740 was all about?

2021-01-24 00:34 UTC, rubenwardy commented
> Then what e.g. #10740 was all about?

That's not a PR. I meant in terms of code review

2021-01-27 22:01 UTC, Zughy commented
Not the right time, as MT clang right now is horrible. Closing

2021-01-27 22:01 UTC, closed without merging

2021-01-27 23:40 UTC, numberZero commented
@Zughy What’s about doing exactly what the title says instead of all that stuff in this PR?

2021-01-28 00:03 UTC, sfan5 commented
There's three options here, only one of which is acceptable:
* Increase the clang-format column limit, don't adjust the code and live with failing CI forever
* Increase the clang-format column limit, adjust all the code and cause hundreds of unnecessary changes
* Do not touch the clang-format config (and instead consider #10863)

If it turns out that all these formatting changes are not due to `ColumnLimit: 105` but the other config changes I will gladly approve a PR for that.