Add Lua metatable-based class helpers
minetest/minetest pull request #10824
Opened 2021-01-18 04:10 UTC by v-rob

Lua has no consistent way to use OOP, leading to many home-baked solutions in mods, all of which are more or less incompatible.  Seeing as metatable-based classes are common enough, this PR adds helper functions to create metatable-based classes including support for inheritance and automatic deep copying of classes.

If this PR needs more justification, the engine likely will have some Lua metatable-based classes with the formspec replacement, and custom elements will require inheritance and deep copying.  So, either this PR (or a similar one) goes through, or the GUI will have to bake its own solution anyway.  So, we might as well make a standard solution beforehand.

Documentation can be seen in the changes to `lua_api.txt`.

## To do

This PR is Ready for Review.

## How to test

A unit test has been added to devtest.  Enable unit testing, and ensure it doesn't fail.

2021-01-18 11:11 UTC, hecktest commented
Is the incompatibility a real problem that has been encountered by users and documented? Home grown solutions are the Lua way, and libraries exist for those who want a unified approach. People will still bolt their own code onto this or replace it because you can never satisfy everyone, and because whoever uses an OOP lib is probably happy with it. Your spin on it isn't bad but it doesn't cover everything. It might end up being analogous to the builtin vector math facilities, that is, not used by anyone who actually knows what they're doing.

Secondly, this is meant to support _The Mythical Formspec Replacement_, but does anyone know what that is actually going to look like, and can I read a specification of it somewhere? If not, are you sure you're gonna need it?

Philosophy aside, here's a real problem: **you're reserving the** `class` **global key which may be in use by existing code**. (I use it, surprise, for my own OOP library)
Therefore any future use of this table by builtin must never assume that the key will not be changed. This means localizing a reference to `class` at the very least. It's either that, or moving the table to a subkey of `minetest`.

2021-01-18 16:35 UTC, benrob0329 commented
It's worth noting that The PIL has [a recommended way of implementing classes](https://www.lua.org/pil/16.1.html) that works and doesn't overcomplicate everything. If people generally stick to this convention, a set of `class` helpers probably isn't needed unless special behavior is needed outside of what metatable inheritance already provides.

I've used this style of prototype OOP, it's as simple as:
```Lua
local MyObject = {}
function MyObject:new(o)
    o = setmetatable(o or {}, {__index = self})

    -- Put any initialization code here like stuff for private variables using closures
end
```

2021-01-18 22:15 UTC, v-rob commented
> Secondly, this is meant to support _The Mythical Formspec Replacement_

I am 99% certain that the formspec replacement will use Lua classes.  I haven't broadcasted it widely, but I've been working on the formspec replacement for months (for visible proof, see #10524, but I've been doing things even before then).  Really, unless I magically disappear sometime in the near future, the formspec replacement is no myth.  It's what I devote nearly all my core development time to.  I can't give a full specification of the API because that hasn't been fully developed, but I know that it will use Lua classes (see #6527; the idea for it being OOP based has been around for quite a while).

Now, I do know for certain what I'm going to need from this library for the actual formspec replacement:
* `class.copy` and `class.copy_into`: A proper deep copy function is necessary for cloning parts of the element tree.  Deep copying should not be necessary for users to implement themselves.  The `__copy` metamethod, or something like it, is also necessary to ensure that elements have unique IDs for communication between the client and server.
* `class.of`: There has to be a simple way to tell if an element is of the specified type.
* `class.new`: Who's to enforce that modders use the proper styles of inheritance and suchlike for custom elements?  It has to be enforced, so an inheritance function must exist.  Sure, we could provide some standard boilerplate code for custom elements to replicate, but that just seems like bad design to me.

The other functions in the class library are mainly small convenience functions.  In other words, much of the same code will be put into the formspec replacement if it isn't put in here.

> I've used this style of prototype OOP, it's as simple as:
> 
> ```lua
> local MyObject = {}
> function MyObject:new(o)
>     o = setmetatable(o or {}, {__index = self})
> 
>     -- Put any initialization code here like stuff for private variables using closures
> end
> ```

This illustrates Lua class incompatibilities perfectly.  This is an example of a closure/metatable approach.  I always use pure metatable.  http://lua-users.org/wiki/ObjectOrientationTutorial has even more possibilities: pure closure, inheritance using copying vs inheritance using `__index` chains, class creation using `.new`, `:new`, `.init`, `:init`, or `__call`, etc.

---

If this PR doesn't go through, I'm not unduly unhappy.  However, I am of the opinion that if something is commonly used by a large proportion of mods so that all the mods have to implement it themselves, it's good for the engine to provide something to cover most of those use-cases.

2021-01-18 22:32 UTC, rubenwardy commented
That's not a closure. Closures are when you have a function registered with upvalues, which is not the case here

2021-01-18 22:57 UTC, v-rob commented
> That's not a closure. Closures are when you have a function registered with upvalues, which is not the case here

Oops, my mistake.  I wasn't paying attention very well.  The comment threw me off.

2021-01-19 07:32 UTC, appgurueu commented
I'm not a fan of this library: Instead of using nested metatables, you are deepcopying methods. This might be slightly beneficial for performance, and probably also a little more flexible (there's a limit on metatable nesting), but it also consumes more memory and complicates some things. Consider classes `A` and `B`, with `B` extending `A` in mods `A` and `B`. In a second mod `C`, which loads after both, you add the method `A:c()`. Now you will also have to do `B.c = A.c`; this wouldn't be required if you had been using nested metatables. Another issues with this are metatables of inherited classes. `modlib` provides a list-based vector implementation, for example. For convenience and compatibility, the indices `x`, `y`, `z` and `w` are effectively aliases for `1`, `2`, `3` and `4`. A `colorspec` can be seen as an extension of a vector. If I was to do `class.new("colorspec", modlib.vector)`, this functionality would be lost.

> It's worth noting that The PIL has [a recommended way of implementing classes](https://www.lua.org/pil/16.1.html) that works and doesn't overcomplicate everything. If people generally stick to this convention, a set of `class` helpers probably isn't needed unless special behavior is needed outside of what metatable inheritance already provides.
> 
> I've used this style of prototype OOP, it's as simple as:
> 
> ```lua
> local MyObject = {}
> function MyObject:new(o)
>     o = setmetatable(o or {}, {__index = self})
> 
>     -- Put any initialization code here like stuff for private variables using closures
> end
> ```

That is pretty much fine. I however prefer `MyObject.new` (`MyObject` is then obtained as upvalue instead of parameter). I would also make `local metatable = {__index = self}` an upvalue - else every object will have it's own metatable.

Finally, I do think that no convention should be forced upon modders by the engine. Compatibility of existing OOP implementations (most of which are basically like @benrob0329's code) is already fairly acceptable.

2021-01-19 14:14 UTC, hecktest commented
Two things:

When people who already use OOP are going to define new elements in this GUI framework, they will most likely wrap your classes in their own classes because... it's incompatible.

Second, are you sure that classes are actually necessary? What if what you actually want is an interface contract, not a class? (which, in lua, requires zero code and is what the API has done the whole time with WhateverSpec definitions)

2021-01-19 16:57 UTC, v-rob commented
> When people who already use OOP are going to define new elements in this GUI framework, they will most likely wrap your classes in their own classes because... it's incompatible.

Anyone who does that deserves any problems they get.  If a mod uses one method for classes, say closures, and I want to inherit from it, I would naturally use closures too, even though I don't particularly like them for classes.  This applies even more so to the engine, where you should always do as you're told in `lua_api.txt` because incorrect behaviour can happen otherwise.  "When in Rome, do as the Romans do."

> Second, are you sure that classes are actually necessary? What if what you actually want is an interface contract, not a class? (which, in lua, requires zero code and is what the API has done the whole time with WhateverSpec definitions)

Yes, I'm quite sure that classes are what I'm going to use.  I require inheritance and virtual functions.  Imagine a `ui.Element` with an inherited `ui.Sizer` overwriting the `ui.Element:layout()` method without changing anything else.  That's more analogous to `MetaDataRef` with inherited `NodeMetaRef`, `ItemStackMetaRef`, etc than e.g. `ColorSpec` or vectors.

> Instead of using nested metatables, you are deepcopying methods.

Well, nesting metatables has problems too.  Metamethods like `__add` do not go up the `__index` chain, but only search the immediate metatable, making those metamethods unusable.  Initializing classes with `__call` therefore becomes impossible, requiring `.new` or whatever (which is inconsistent with the rest of the engine; do you use `Raycast.new()`?  No, it's `Raycast()`).  Multiple inheritance isn't possible (although that's not a huge loss).  And, of course, they're slower.

However, deep copying only does one thing as you noted: makes it impossible to extend classes.  I don't think that should be done anyway; a mod extending another mod's class and especially extending a built in UI element would be analogous to a mod trying to extend `MetaDataRef` (which wouldn't extend `NodeMetaRef` automatically since it doesn't use `__index`, just like here).  It shouldn't be done because it's a) bad design and b) can break things if functionality is added to those other classes later.

So, I will use deep copying for the UI and not `__index` chains whether this is merged or not.

2021-01-19 17:02 UTC, appgurueu commented
> Multiple inheritance isn't possible (although that's not a huge loss)

That is wrong. The entire point of metatables is basically to have "default" values for certain fields. How multiple inheritance could work:

* `{__index = {__index = ...}}`
* `{__index = function(self, key) for _, superclass in ipairs(...) do local value = superclass[key]; if value ~= nil then return value end end return rawget(class[key])`

2021-01-19 17:26 UTC, v-rob commented
> That is wrong. The entire point of metatables is basically to have "default" values for certain fields. How multiple inheritance could work:
> 
> * `{__index = {__index = ...}}`
> * `{__index = function(self, key) for _, superclass in ipairs(...) do local value = superclass[key]; if value ~= nil then return value end return rawget(class[key]) end`

OK, but why should modders have to write that function every time they need multiple inheritance?  Wouldn't it be nice if there was a _helper function_ to do it for them?  Gee, that would be nice.

Plus, the suggestion to just use PIL's methods for OOP fails here because this _isn't_ PIL's method.  PIL has no method for multiple inheritance.  PIL has no method for inherited `__add`.  Plus, PIL suggests `:new`, but I've already seen someone who disagrees and uses `.new`.  PIL's way of doing it is far from a standard.

2021-01-19 17:30 UTC, rubenwardy commented
For reference, here's a helper function I wrote for the :new() metatable way of doing classes: https://gitlab.com/rubenwardy/lua_ext/-/blob/master/class.lua

> I however prefer MyObject.new

MyClass:new() is needed to support inheritance. You can inherit by doing

```lua
SubClass = MyClass:new()

function SubClass:thing()
	return 3
end


local obj = SubClass:new()
print(obj:thing())
```

2021-01-19 17:43 UTC, appgurueu requested changes

2021-01-19 17:43 UTC, appgurueu commented on builtin/common/class.lua
> +	cls.__name = name
Why? This becomes problematic if there is `scope_a.class` and `scope_b.class`: both will have the same name.

2021-01-19 17:43 UTC, appgurueu commented on builtin/common/class.lua
> +	local self = class.instantiate(cls)
I don't like this at all, as it requires unnecessary tablecopies: I like to have constructors like `MyClass{a = 1}`, which directly set the metatable for the passed table.

2021-01-19 17:43 UTC, appgurueu commented on builtin/common/class.lua
> +		return mt -- An object was passed
Shouldn't this always expect an object? Might be nicer as getter implemented using `__index` (`object.prototype == MyClass`). I think however that such a method should not be required and that instead `getmetatable` is to be used.

2021-01-19 17:43 UTC, appgurueu commented on builtin/common/class.lua
> +	setmetatable(obj, cls)
The only possible benefit of this wrapper might be in readability.

2021-01-19 17:43 UTC, appgurueu commented on doc/lua_api.txt
> +    local MyClass = class.new("MyClass")
Shouldn't this be `class"MyClass"` ;)

2021-01-19 17:43 UTC, appgurueu commented on builtin/common/class.lua
> +	-- Copy inherited classes in reverse order to make the first ones overwrite later ones
I would still prefer nested metatables, or possibly a combined approach to allow inheriting metamethods. If chains get long enough to negatively affect performance, that is on the modder (there is a limit on chain length imposed by Lua though).

2021-01-19 17:59 UTC, v-rob commented
> I'm not sure that multiple inheritance is needed or desirable

That's why I said it's not a huge loss.

> I wonder if you could set the metatable's metatable

Right, but then for inheritance, you're making a copy of the metamethods that start with `__` and putting them into a metatable which is set on the original metatable.  At that point, why not deep copy everything?

> perhaps simpler is better

I think that `local MyClass = class.new("MyClass")` looks pretty simple, simpler than PIL's boilerplate code method, but I guess that's a matter of opinion.

---

I guess there's no point in arguing this anymore.  There's no consensus on classes (and no, I maintain that PIL's is not a fully consistent solution), so this might as well be closed.  I have no idea how a consensus will be reached on the UI's API, but I guess that's a hurdle to be overcome later.  Oh well.

2021-01-19 17:59 UTC, closed without merging

2021-01-20 22:57 UTC, benrob0329 commented
For posterity and example's sake, I have put together a snippet of PIL-style OOP which shows multi-inheritance and private members. This should be roughly compatible with other metatable-based `:new()`-style classes without extra effort.

```Lua
-- Base Classes Which Do Not Inherit --
local ClassA = {a = 1, b = 2, c = 3}
function ClassA:new(o)
	o = setmetatable(o or {}, self)
	self.__index = self

	-- Private Members
	local private = 42
	function o:getPrivate()
		return private
	end

	return o
end

local ClassB = {a = 9, d = 4}
function ClassB:new(o)
	o = setmetatable(o or {}, self)
	self.__index = self
	return o
end

-- Class Which Inherits From Both --
local ComboClass = {}
function ComboClass:new(o)
	o = ClassA:new(o)
	o = ClassB:new(o)

	setmetatable(o, self)
	self.__index = function(t,k)
		return ClassB[k] or ClassA[k]
	end

	return o
end

-- Instance Of Said Combo Class --
local MyObject = ComboClass:new()
print(MyObject.a, MyObject.b, MyObject.c, MyObject.d)

-- Class Which Inherits From The Multiinheritance Class --
local SubComboClass = ComboClass:new()
function SubComboClass:new(o)
	o = ComboClass:new(o) -- Run Parent's Initilization Function Since We're Defining A New One

	o = setmetatable(o, self)
	self.__index = self

	return o
end

function SubComboClass:printSum()
	print(self.a + self.b + self.c + self.d)
end

-- Instance Of Said Class --
local MySubObject = SubComboClass:new()
MySubObject:printSum()
print(MySubObject:getPrivate())
```