Add Metrics API
minetest/minetest pull request #10980
Opened 2021-02-19 21:20 UTC by rubenwardy

Add compact, short information about your PR for easier understanding:

- Goal of the PR
- How does the PR work?
- Does it resolve any reported issue?
- If not a bug fix, why is this PR needed? What usecases does it solve?

## To do

This PR is a Work in Progress / Ready for Review.

- [ ] List
- [ ] Things
- [ ] To do

## How to test

2021-02-23 14:53 UTC, nerzhul requested changes

2021-02-23 14:53 UTC, nerzhul commented on src/map.h
> -	MetricCounterPtr m_save_time_counter;
warning, you have both MetricCounter & MetricGauche in prometheus. If you remove the meaning here, we don't know what is this

2021-02-23 14:53 UTC, nerzhul commented on src/util/metricsbackend.h
> +	virtual MetricPtr addCounter(const std::string &name, const std::string &help_str,
if you remove the Counter, it's implicit, and it's not implicit in any other prometheus API. Counter is not generic

2021-02-23 15:11 UTC, rubenwardy commented
Should I add an empty class MetricCounter for this, which derives from Metric? Seems unnecessary. I need a unified interface in order to cleanly add MetricRef. Counter has all the base behaviour, it's gauge which then allows set() and decrement()

2021-03-01 17:03 UTC, nerzhul commented
There is no histogram or summary in prometheus, it's done by the queries on the prometheus server, it's why it's simple.
Ok for the rename.
Can you look at adding binding to remove metrics ? In some cases it's useful. For example in a such case:

metric_a{label_a="toto", state="running"}=1
metric_a{label_a="toto", state="stopped"}=1
You must drop one of the metric in order to setup the other metric labeled to 1, or set to zero but it's not in the best practices

2021-03-01 17:05 UTC, nerzhul requested changes
see my comment before

2021-06-01 01:46 UTC, closed without merging

2021-12-01 01:51 UTC, erlehmann commented
@rubenwardy why was this closed?

2022-05-05 19:28 UTC, rubenwardy commented
> @rubenwardy why was this closed?

A lot of effort for something that won't effect many users and doesn't seem that supported