Detect interacting with yourself
minetest/minetest pull request #11137
Opened 2021-03-29 21:05 UTC by appgurueu

Detects & blocks interactions with yourself. Use any hacked client and punch yourself to test this.

2021-03-29 21:13 UTC, sfan5 commented
I'd rather put these in `src/network/serverpackethandler.cpp`
Also you might want to add a message like so
https://github.com/minetest/minetest/blob/fde2785fe363c55e8acfd17af71375a231df41c1/src/network/serverpackethandler.cpp#L974-L975

2021-03-29 21:40 UTC, sfan5 requested changes
:+1: if changed

2021-03-29 21:40 UTC, sfan5 commented on src/network/serverpackethandler.cpp
> +				actionstream << player->getName() << " attempted to interact with themself" << std::endl;
```suggestion
				actionstream << "Server: " << player->getName()
					<< " attempted to interact with themselves" << std::endl;
```

2021-03-30 19:49 UTC, merged

2021-03-30 20:20 UTC, appgurueu commented
@gnu9d ooh, your hack client ceases to work for this. cry me a river.