Ignore mod dirs starts with an underscore (`_`)
minetest/minetest pull request #11242
Opened 2021-05-04 06:14 UTC by Emojigit

Close #11240, to ignore mod dirs starts with an underscore (`_`)

## To do

This PR is Ready for Review, please help me to test it.

- [x] Ignore mod dirs starts with an underscore (`_`)

## How to test

Create a mod with these dirs:
```
example_mod/
├── _docs
├── .hidden_file
├── modpack.conf
├── real_mod
│   ├── init.lua
│   ├── mod.conf
│   └── textures
│       └── real_textures.png
└── _test
```
Note that `_docs`, `_test`, and `.hidden_file` will not show in neither mod menu nor `world.mt`.

2021-05-07 02:06 UTC, Wuzzy2 commented
:-1:
This will break MCL2, which currently intentionally uses mod dirs that start with an underscore. Underscore is one of the few characters allowed in mod names.

Why not choose a character that is illegal in mod names anyway?

2021-05-10 09:08 UTC, SmallJoker commented
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/src/content/mods.h#L34

2021-05-13 07:37 UTC, Emojigit commented
> This will break MCL2, which currently intentionally uses mod dirs that start with an underscore. Underscore is one of the few characters allowed in mod names.

@Wuzzy2 Slove by changing the prefix to tilde

2021-05-14 02:15 UTC, Wuzzy2 commented
Good.

2021-05-15 08:16 UTC, nerzhul commented
The change must be documented somewhere in the mod documentation, else nobody will know this :)

2021-05-15 08:16 UTC, nerzhul requested changes
documentation to add, comment in the code is not sufficient

2021-05-15 10:34 UTC, sfan5 commented
I'm not sure if `~` is a good choice, on Unix systems it can refer to user home folders in certain contexts.
And if `.` already works why do we need a second one?

2021-05-15 12:54 UTC, Wuzzy2 commented
The tilde being used for the home directory is mostly a shell-thing, and even here it can just be escaped. The tilde is a legal character for directories, after all. That having said, I agree it would probably still be better to pick another character, just to avoid unneccessary confusion. The dot actually seems to be a much better idea.

2021-05-15 18:37 UTC, ryvnf commented
I think the motivation for including another character than dot is to allow having directories which are not hidden under Unix but are also not loaded as mods. I am not sure this is worth adding but if it is desired then I think there are better ways that relying on the directory name. Here are two other approaches which I think would be better because they do not require having ugly characters like ~ (tilde) in the directory names.

### 1. Ignore directories which do not contain mod files

Check for the existence of init.lua, mod.conf or any other file suggesting that the directory is a mod (or modpack) and ignoring the directory if it does not contain such files.

### 2. Add an option to modpack.conf

Another approach would be to add a flag in modpack.conf that specifies the directory for the mods. For example:

```
name = my_modpack
mods_dir = mods
```

In the above example mods would only be loaded from the directory named mods. All other directories are ignored and can be used for tests, documentation or anything else.

2021-05-15 20:18 UTC, sbrl commented
@ryvnf: I like that idea to ignore directories that don't contain an `init.lua`. That seems like the best solution to me.

The tilde would potentially work as a workaround - though it does have the problem that @sfan5 mentions about needing to escape it on Linux-based systems. Maybe a colon `:` or a plus `+`? Though I haven't seen that done elsewhere.

I wasn't aware that a dot `.` at the beginning causes a directory to be ignored, but the problem there as @ryvnf mentions is that dots at the beginning of things on Linux cause things to be hidden, which is not desirable for documentation for example.

2021-05-20 08:51 UTC, Emojigit commented
Other solving way: `ignore = true` in `mod.conf`

2021-05-27 09:39 UTC, Emojigit commented
@sbrl Another workaround is to create a blank `init.lua` file.

2021-05-27 23:23 UTC, sbrl commented
Oh, I wasn't aware of `ignore = true`. Is that documented anywhere?

2021-06-19 15:09 UTC, SmallJoker commented
Adding more special files or lines seems like a hacky workaround to me. `~` is a regular character in UNIX/Linux systems. Shells ( `dash` and `bash` tested) only seem to resolve it to `$HOME` when the tilde is either alone or appended by a slash.

`.` directories are by default hidden in various file managers, hence it would really make sense to have a secondary character which can be used. I do not see any issue with the tilde character so far, so I'd welcome this change.

2021-09-20 23:31 UTC, sfan5 commented
Just stumbled upon this today (again) while creating a folder to hold CI scripts.

> Other solving way: `ignore = true` in `mod.conf`

This doesn't do anything, the mod still appears in the menu.
I would however support implementing such a solution. It would give modders full control what to name folders and not unnecessarily block those mod names from being used elsewhere.

2021-10-31 19:46 UTC, rubenwardy commented
I'd prefer `-` to `~`, but a way of ignoring dirs would also be good. It's common to use files like `.dockerignore` to ignore stuff, so we could have `.mtignore` to ignore. I'd prefer this to an erroneous `mod.conf` file

2021-11-19 12:52 UTC, closed without merging