Add API for mods to hook liquid transformation events
minetest/minetest pull request #11405
Opened 2021-06-29 23:33 UTC by Warr1024

Make it possible for mods to detect liquid transformation changes to the map without resorting to polling.

Add a register_on_liquid_transformed() hook to the server-side modding API.  If at least one function is registered, call it, passing a list of all nodes that were transformed by the liquid transform process.  This list was already generated by the liquid transform system, so converting it to a lua table was all that was necessary (conversion skipped if no hooks).

Resolves #11399

## Use-Cases

NodeCore: sensing fluid flow movement by blocking/unblocking optics beams for automation.  Possibly other recipes involving liquids (e.g. quenching heated metals).

Minetest Game: Possibly lava quenching (depending on performance trade-offs)

## To do

This PR is Ready for Review.

## How to test

### Use case:

- Install the `fluidhook` branch of **NodeCore** (https://gitlab.com/sztest/nodecore/-/tree/fluidhook)
- Download this test world and load it: [ncfluidtest.tar.gz](https://github.com/minetest/minetest/files/6737039/ncfluidtest.tar.gz)
- Watch the timing between the two circled nodes: 
![fluidwatch](https://user-images.githubusercontent.com/324806/123880210-2a75cf00-d910-11eb-82a5-ed3d1bd5b2ae.png)

**Without** this PR merged, you will notice a delay of a second or two between the molten glass (blue circle) flowing in and the prism (red circle) switching off, and between the molten glass flowing out and the prism switching on.  This delay may vary based on lag; creating artificial lag on the server, especially using ABMs, can expand this time gap significantly.

**With** this PR merged, the delay should always be less than half a second.

### Non-use case:

Load up any other world with any other game that is NOT using the functionality in this PR.  Place lots of liquid nodes high up, e.g. at the top of mountains, such that they will flow out over long distances.  You should not notice any difference in behavior regardless of whether this PR is merged or not.

2021-07-02 13:30 UTC, celeron55 requested changes
I think this is fine with the two code changes (comments in the code), but the API is a bit controversial so we should allow some time for others to decide whether to propose a different API.

2021-07-02 13:30 UTC, celeron55 commented on src/script/cpp_api/s_env.cpp
> +		lua_createtable(L, 0, 3);
Why isn't pushnode() used?

2021-07-02 13:30 UTC, celeron55 commented on src/script/cpp_api/s_env.cpp
> +	std::vector<std::pair<v3s16, MapNode> > &list)
Argument should probably be const

2021-07-02 14:08 UTC, sfan5 commented on src/script/cpp_api/s_env.h
> +#include "util/container.h"
`#include <vector>` is enough here

2021-07-02 14:59 UTC, celeron55 approved these changes

2021-07-03 08:09 UTC, hecktest commented
Code looks good.
Suggestion: give the callback two parallel arrays, one of nodes and one of positions, to reduce the amount of tables that are constructed.

2021-07-07 15:06 UTC, AFCMS commented
:+1: mcl2 will also benefit of this feature

2021-07-09 13:08 UTC, merged