Add paramtype2s for horizontal rotation and 64 colors
minetest/minetest pull request #11431
Opened 2021-07-07 22:31 UTC by Wuzzy2

This PR adds 2 paramtype2s: `4dir` and `color4dir`.

`4dir` is like `facedir`, but only for 4 horizontal directions: NESW. It is identical in behavior to `facedir` otherwise. The reason why game makers would want to use this over `facedir` is 1) simplicity and 2) you get 6 free bits.
It can be used for things like chests and furnaces and you don't need or want them to "flip them on the side" (like you could with facedir).

`color4dir` is like `colorfacedir`, but you get 64 colors instead of only 8.

Also, as with all color paramtype2s, the builtin functions were updated accordingly.

For details on how this works, see the commits (`lua_api.txt`). Documentation for `facedir` and `wallmounted` is also updated to distinguish those better from `4dir`.

## To do

This PR is ready for review.

Many test cases in DevTest were added which I used for testing in depth. I tested rotation (obviously), color, falling node, and all new nodes I added to DevTest. I also tested the new and modified builtin functions (but you should, too!). It all seems to work to me.

One thing I didn't test in depth is the prediction. I am not so sure if the placement prediction code is correct, please some verify the logic. I don't know how test this part. It would also help me if you have a hint for me on how I can test predition better (I think I basically need to simulate a lag or something ...).

## How to test

Use DevTest and use the many 4dir nodes and the Param2 Tool to modify them. Compare with facedir param2 values 0 to 3, it MUST look the same.
Test if the nodes still look OK when falling (use Falling Node Tool).
Use DevTest and `luacmd` mod to test all the functions I modified.

2021-07-12 18:40 UTC, hecktest commented
How about calling it `coloryaw` since it's just around the Y axis?

2021-07-12 20:45 UTC, Wuzzy2 commented
I don't really care either way. It depends on what others think. If enough people are for it, I change it. If not, then not.

2021-07-14 18:26 UTC, Wuzzy2 commented
Note: This PR should have a concept approval because #6194 is "supported by core dev".

2022-01-10 12:05 UTC, Wuzzy2 commented
Bump.

2022-01-10 15:39 UTC, SmallJoker commented
Rebase needed.

2022-01-10 20:39 UTC, Wuzzy2 commented
Rebased.

2022-03-08 23:22 UTC, Df458 commented
Starting to look at this today. Haven't seen anything too out of the ordinary, but haven't done much with it yet.
From a first look, this seems fine:
![4dirs](https://user-images.githubusercontent.com/2219707/157342591-88a41953-75c9-4c41-85be-0cf0c3ed9c74.png)

2022-03-09 22:26 UTC, Df458 requested changes

2022-03-09 22:26 UTC, Df458 commented on src/client/game.cpp
> +			predicted_f.param_type_2 == CPT2_FACEDIR) {
```suggestion
			predicted_f.param_type_2 == CPT2_COLORED_4DIR) {
```

2022-03-09 22:26 UTC, Df458 commented on src/mapnode.cpp
> +		} else {
Consider a comment or redundant `else if` for 4dir, in case of future paramtype2s

2022-03-09 22:26 UTC, Df458 commented on src/nodedef.cpp
> +					features.param_type_2 == CPT2_COLORED_4DIR) {
```suggestion
					features.param_type_2 == CPT2_COLORED_FACEDIR ||
					features.param_type_2 == CPT2_4DIR ||
					features.param_type_2 == CPT2_COLORED_4DIR) {
```

2022-03-09 22:26 UTC, Df458 commented on src/nodedef.cpp
> +			} else  {
Consider a comment or redundant `else if` for 4dir, in case of future paramtype2s

2022-03-09 22:27 UTC, Df458 commented
Did some further testing, including a test of round-tripping various vectors through `dir_to_fourdir` and `fourdir_to_dir`, no issues on that end.

2022-03-15 00:59 UTC, Wuzzy2 commented
@Df458: Done.

2022-03-15 20:37 UTC, Df458 approved these changes
Looks good to me now

2022-05-28 23:01 UTC, Zughy commented
@Wuzzy2 please rebase

2022-05-29 12:52 UTC, Wuzzy2 commented
@Zughy: Rebase complete!

2022-08-29 20:14 UTC, x2048 commented
Tested and reviewed, but a rebase needed. I've pushed rebased branch [here](https://github.com/x2048/minetest/tree/4dir).

@Wuzzy2

2022-09-08 14:42 UTC, Wuzzy2 commented
Rebase done. Testing needed.

2022-09-09 11:38 UTC, Zughy commented
@Wuzzy2 please either remove the label by yourself or quit from being a triager, this is not the first time it happens

2022-09-16 11:18 UTC, merged

2022-09-28 20:40 UTC, Wuzzy2 commented
Follow-up PR for Minetest Game: #2992