HUD: Do not assume int values on unknown HUD types
minetest/minetest pull request #11548
Opened 2021-08-17 17:48 UTC by SmallJoker

Trivial fix for #11539

## To do

This PR is Ready for Review.

## How to test

1. Check whether  HUD element changes still work, for example using `/testhud` in devtest

2021-08-17 19:04 UTC, AFCMS commented
Why `WIP` label and "Ready for review" ?

2021-08-17 21:15 UTC, sfan5 commented on src/network/clientpackethandler.cpp
> +	}
This is broken, there's a `return;` at the end.

2021-08-17 21:16 UTC, sfan5 commented on src/script/common/c_internal.h
> +void log_deprecated(lua_State *L, std::string message, int stack_dept = 1);
```suggestion
void log_deprecated(lua_State *L, std::string message, int stack_depth = 1);
```

2021-08-19 14:44 UTC, nerzhul requested changes

2021-08-19 14:44 UTC, nerzhul commented on src/network/clientpackethandler.cpp
> +			return;
replace with break, else you discard data

2021-08-19 17:13 UTC, sfan5 commented
I don't see anything logged when executing `executed core.get_player_by_name("singleplayer"):hud_change(3, "WRONG", 1)` though the hud packet doesn't go out.

2021-08-19 17:57 UTC, sfan5 approved these changes

2021-08-21 18:04 UTC, merged