Remove ancient debug comments
minetest/minetest pull request #12119
Opened 2022-03-06 20:00 UTC by otakubeam

I hope it's nothing too important

2022-03-06 20:21 UTC, otakubeam commented
I just realized applying clang-format is unnecessary because it would just muddle git blame output

2022-03-08 17:19 UTC, sfan5 commented
Indeed, please don't apply clang-format to files you changed.
Also feel free to grep the entire codebase for any commented out stuff that prints to `dstream`.

2022-03-09 18:21 UTC, SmallJoker commented
Fine by me, as long the PR is not squashed.

2022-05-30 21:53 UTC, appgurueu commented
@Zughy I don't see which action would be needed? The commits are neatly separated, have decent commit messages (IMO) and  were apparently considered fine by @SmallJoker.

2022-05-30 22:11 UTC, Zughy commented
@appgurueu My interpretation of `but requires good commit messages` is that right now those names aren't good. Was I wrong? :thinking:

2022-05-31 07:04 UTC, nerzhul requested changes

2022-05-31 07:04 UTC, nerzhul commented on src/voxel.cpp
> +#include <cstring> // memcpy, memset
you can also drop those comments, IDE are here for that, no need to comment headers

2022-05-31 07:04 UTC, nerzhul commented on src/voxel.cpp
> +// END
i don't see the point to keep this comment too, a comment to define end of the file ? :p

2022-06-12 11:34 UTC, Zughy commented
OP has disappeared, closing

2022-06-12 11:34 UTC, closed without merging