Fix possible unreliable behavior due to uninitialized variables
minetest/minetest pull request #12297
Opened 2022-05-08 17:09 UTC by Endi0n

This PR fixes a possible unreliable behavior due to the uninitialized variable row.nodeMeta, and improves code-clarity.

2022-05-08 17:17 UTC, sfan5 requested changes

2022-05-08 17:17 UTC, sfan5 commented on src/rollback.cpp
> +		if (row.type == RollbackAction::TYPE_SET_NODE) {
it's apparent that this part is meant to apply for both `TYPE_MODIFY_INVENTORY_STACK` and `TYPE_SET_NODE`, so this change is just plain incorrect

2022-05-08 17:17 UTC, sfan5 commented on src/rollback.cpp
> +		if (row.type == RollbackAction::TYPE_SET_NODE) {
same here, this is the wrong way around

2022-05-09 20:17 UTC, sfan5 commented on src/rollback.cpp
> +		row.nodeMeta  = sqlite3_column_int  (stmt, 8);
this is probably fine but I think initializing nodeMeta to `0` here and keeping the rest is even better

2022-05-10 16:07 UTC, sfan5 approved these changes
Looks good, thanks.

2022-05-10 20:36 UTC, merged

2022-05-10 21:56 UTC, Endi0n commented
Thank you very much! It was a great learning experience!