Replace all uses of core::list with std::list
minetest/minetest pull request #12313
Opened 2022-05-10 09:47 UTC by paradust7

Part of https://github.com/minetest/minetest/issues/12312

2022-05-16 19:12 UTC, sfan5 approved these changes

2022-05-18 10:35 UTC, nerzhul requested changes
please fix build too

2022-05-18 10:35 UTC, nerzhul commented on src/gui/mainmenumanager.h
> -		/*core::list<GUIModalMenu*>::Iterator i = m_stack.getLast();
just remove this commented part

2022-05-18 11:46 UTC, paradust7 commented on src/gui/mainmenumanager.h
> -		/*core::list<GUIModalMenu*>::Iterator i = m_stack.getLast();
done

2022-05-18 11:47 UTC, paradust7 commented
The build is broken because it depends on the corresponding irrlicht change: https://github.com/minetest/irrlicht/pull/105

2022-05-21 19:07 UTC, rubenwardy approved these changes

2022-05-21 22:11 UTC, merged