Add mesh-holding blocks to shadow drawlist.
minetest/minetest pull request #13203
Opened 2023-02-13 17:41 UTC by lhofhansl

Just like the regular drawlist, the shadow drawlist needs to have the mesh-holding blocks added to it. Otherwise some meshes (i.e. parts of the shadows) will not be displayed.

## How to test

Set client_mesh_chunk to a large value (like 8 or 16), enable shadows, see how most shadows are not displayed without this PR.
With the PR shadows are displayed correctly.
This also happens with smaller client_mesh_chunk sizes (anything larger than 1), it's just harder to notice.

2023-02-15 18:26 UTC, lhofhansl commented
This can as much as double the time spent in updateDrawListShadow. At the same time, I do not see a way around.
Any ideas @x2048 ?

2023-02-15 18:52 UTC, x2048 commented
Our mesher could mark the blocks contributing to the mesh, to optimize this and other cases when mesh should not be considered

2023-02-15 19:05 UTC, lhofhansl commented
Actually. When client_mesh_chunk is set to 1, updateDrawListShadow is slower anyway (in my same test up to 10ms and without this PR).
We're only losing out on a bit of optimization when it is set to > 1, but it is still faster than the = 1 case.

So I think this is still good as is.

> Our mesher could mark the blocks contributing to the mesh, to optimize this and other cases when mesh should not be considered

Yep. That's a good idea here and also for the normal updateDrawList. Let's do that in another PR.
Bit tricky when a mesh gets replaced, would need find all contributing blocks and update them...

2023-02-15 19:42 UTC, x2048 commented
QueuedMeshUpdate has a list of all relevant blocks, and we can patch them when releasing the references.

2023-02-15 20:35 UTC, lhofhansl commented
Let's do that in a different PR. As I suggested above, it probably would not help with this one anyway.

How about this one? Good to merge?

2023-02-16 08:01 UTC, x2048 requested changes

2023-02-16 18:36 UTC, x2048 approved these changes

2023-02-16 18:37 UTC, x2048 commented
Looks good. Did not test.

2023-02-17 01:43 UTC, merged