Added support for more parameters in mod.conf
minetest/minetest pull request #13230
Opened 2023-02-19 05:44 UTC by arihant2math

Add compact, short information about your PR for easier understanding:

Adds support for a website and license in mod.conf as per #9395
## To do

This PR is a Work in Progress 

- [ ] Add license support
- [ ] Fix website format checking
- [ ] Add details to mod display

2023-02-19 07:04 UTC, arihant2math commented
Waiting for #12926 before adding links to the license and website. I feel that linting the license isn't really needed for now.

2023-02-19 16:38 UTC, rubenwardy commented
This should be added to game.conf and texture_pack.conf too, and be part of get_content_info and ContentSpec rather ModSpec

2023-02-19 20:43 UTC, arihant2math commented
Moved it to `ContentSpec` only, this should work.

2023-05-29 11:30 UTC, srifqi commented on doc/lua_api.txt
> +* `license`: The mods license, should be a SPDX identifiers
```suggestion
* `website`: The mod's website. It must start with either "http://" or "https://"
             in order to be displayed.
* `license`: The mod's license. It should be an SPDX identifier if possible.
             See https://spdx.org/licenses/
```

2023-06-04 23:35 UTC, arihant2math commented
Fixed merge conflicts (hopefully)

2023-06-05 00:20 UTC, srifqi requested changes
Please check the rebasing of this PR (do **not** merge branch) to current `master` branch. You can read more [here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

The `lua_api.txt` has been converted to `lua_api.md`. The documentation for the Modding API now goes there.

-------

Also, can we make it uniform whether the website or the license that should go first? The order is different between files.

2023-06-11 04:30 UTC, arihant2math commented
Rebase complete, reapplying changes to `lua_api.md`

2023-06-11 04:34 UTC, arihant2math commented
ok, ported the changes.

2023-06-11 07:00 UTC, srifqi requested changes
Sorry, but please rebase this PR (do **not** merge branch) to current `master` branch. It should only consists of your commits (around 15 in this PR) to make reviewing easier. You can read more [here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

2023-07-10 21:08 UTC, closed without merging

2024-01-10 01:59 UTC, JamesClarke7283 commented
Why was this PR closed?

2024-01-10 10:19 UTC, Zughy commented
@JamesClarke7283 author's gone