Add `vector.contains()` utility function
minetest/minetest pull request #13390
Opened 2023-04-05 15:07 UTC by AFCMS

Fix #13366 (@Zughy 's proposal)

## To do

- [x] Add function
- [x] Add `lua_api.txt` entry

## How to test

```lua
-- Check is works exactly like `VoxelArea:contains()`
assert(vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.zero()))
assert(vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-2, 5, -8)))
assert(vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-10, -10, -10)))

-- This test should not pass
-- assert(vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-11, -10, -10)))
```

2023-04-05 16:05 UTC, AFCMS commented
> 

I just did a quick benchmark and it seems 2x slower:

In `vector.lua`:
```lua
function vector.contains(v1, v2, pos)
	return (pos.x >= v1.x) and (pos.x <= v2.x) and
		(pos.y >= v1.y) and (pos.y <= v2.y) and
		(pos.z >= v1.z) and (pos.z <= v2.z)
end

function vector.contains2(v1, v2, pos)
	local cp1 = vector.new(pos-v1):cross(v2-v1)
	local cp2 = vector.new(pos-v2):cross(v1-v2)
	return cp1:dot(cp2) < 0
end
```

```lua
minetest.register_chatcommand("bench_vec", {
	description = "Benchmark vector contains",
	func = function(name, param)
		local time = minetest.get_us_time()
		for i = 1,20000 do
			vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.zero())
			vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-2, 5, -8))
			vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-10, -10, -10))
		end
		minetest.chat_send_all("and:  "..tonumber(minetest.get_us_time()-time))

		local time = minetest.get_us_time()
		for i = 1,20000 do
			vector.contains2(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.zero())
			vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-2, 5, -8))
			vector.contains(vector.new(-10, -10, -10), vector.new(10, 10, 10), vector.new(-10, -10, -10))
		end
		minetest.chat_send_all("cross + dot:  "..tonumber(minetest.get_us_time()-time))

		return true, "Done."
	end,
})
```

Getting this result (tried multiple times, similar results):
![image](https://user-images.githubusercontent.com/61794590/230138436-b9533166-b7cd-44c7-ace4-5aaa62eefb97.png)

I am using LuaJIT in case it affects the result (fork updated with the latest master branch).

```
Minetest 5.7.0-dev-08c0f3f-dirty (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

2023-04-06 00:37 UTC, Andrey2470T commented
What if e.g. `v1.x > pos.x > v2.x` (the comparison is directed along -X axis) ? That would return false in your code, however it is true, just in other direction.

I'd suggest so:
`
local function is_within(s, e, v)
    return (math.min(s, e) <= v) and (v <= math.max(s, e))
end

function vector.contains(v1, v2, pos)
    return is_within(v1.x, v2.x, pos.x) and
        is_within(v1.y, v2.y, pos.y) and
        is_within(v1.z, v2.z, pos.z)
end
`

2023-04-06 06:39 UTC, AFCMS commented
There is also this proposal https://github.com/minetest/minetest/issues/13171#issuecomment-1420678776

```lua
function vector.in_area(v, a, b)
	local p, q = vector.sort(a, b)
	return p.x <= v.x and v.x <= q.x and p.y <= v.y and v.y <= q.y and p.z <= v.z and v.z <= q.z
end
```

I did some testing with it and it takes roughly 2x more time (similar to @kilbith2 's solution).

I honestly think we should assume p1 is min and p2 is max to avoid this check. Most of the time you already know which are the min and the max. When creating a VoxelArea there is no check like that.

In that case it would be better to rename `p1` to `min` and `p2` to `max` in the docs to make it clear.

@Zughy opinions?

2023-04-06 07:24 UTC, AFCMS commented
> I like `in_area` because it makes using the `:` form make more sense

:+1: Didn't think about this when choosing the params order, will change.

2023-04-06 15:35 UTC, fluxionary commented
redid the benchmarks to try to reduce the effects of branch prediction:

```lua
function vector.contains(pos, v1, v2)
	v1, v2 = v1:sort(v2)
	return (pos.x >= v1.x) and (pos.x <= v2.x) and
		(pos.y >= v1.y) and (pos.y <= v2.y) and
		(pos.z >= v1.z) and (pos.z <= v2.z)
end

function vector.contains2(pos, v1, v2)
	local cp1 = (pos-v1):cross(v2-v1)
	local cp2 = (pos-v2):cross(v1-v2)
	return cp1:dot(cp2) < 0
end

function vector.contains3(pos, v1, v2)
	return VoxelArea(v1, v2):containsp(pos)
end

local function test(name, method, test_vectors)
	local vmin = vector.new(-10, -10, -10)
	local vmax = vector.new(10, 10, 10)

	local time = os.clock()
	for _ = 1,10000 do
		for i = 1, #test_vectors do
			method(test_vectors[i], vmin, vmax)
		end
	end
	local elapsed = os.clock()-time
	print(string.format("%s: %s", name, math.round(elapsed * 1e6)))
end

local test_vectors = {}
for _ = 1, 1000 do
	-- about 60% inside, 40% outside
	table.insert(test_vectors, vector.new(math.random(-12, 12), math.random(-12, 12), math.random(-12, 12)))
end

test("sort+and", vector.contains, test_vectors)
test("cross+dot", vector.contains2, test_vectors)
test("voxelarea", vector.contains3, test_vectors)
```

results varied a little between runs, but were typically something like

![image](https://user-images.githubusercontent.com/25628292/230427479-b2643b09-841e-41c3-bf8a-b38ffc39b9d9.png)

"cross+dot" was the clear winner.

2023-04-06 19:51 UTC, AFCMS commented
> redid the benchmarks to try to reduce the effects of branch prediction:

On your test without the sorting (just the and checks) I get extreme variations sometimes, but it seems to be equal to the "cross+dot" version. So I guess its better to have the sorting if it doesn't take extra time.

2023-04-07 07:46 UTC, AFCMS commented
Strange, but it seems the following tests (based on my own tests, just with reordered parameters) do not pass with the cross + dot version...

```lua
assert(vector.contains(vector.zero(), vector.new(-10, -10, -10), vector.new(10, 10, 10)))
assert(vector.contains(vector.new(-2, 5, -8), vector.new(-10, -10, -10), vector.new(10, 10, 10)))
assert(vector.contains(vector.new(-10, -10, -10), vector.new(-10, -10, -10), vector.new(10, 10, 10)))
```

2023-04-07 14:02 UTC, Desour commented
The cross and dot thing is interesting, but for correct handling of special cases (and for simplicity) it's probably better to just go with the `min <= p <= max`. If someone has really hard performance constraints and uses this function often, they can implement their own thing.

----

As for the min-max sorting, I'd prefer no sorting, for multiple reasons, most important ones being:
* `p:in_area(vector.sort(p1, p2))` isn't that much worse to write than `p:in_area(p1, p2)`.
* With the explicit `vector.sort` in the calling code, the reader gets extra information that these might be in reverse order.
* One could assume that `p:in_area(vector.new(0,0,0), vector.new(0,0,-1))` always returns false because it's an empty area.
* With sorting, empty areas are not possible (or only possible with some hackery like using nan).

That being said, the behaviour if min,max are not sorted should be defined and specified in doc.

2023-04-07 16:24 UTC, fluxionary commented
> do not pass with the cross + dot version...

> The cross and dot thing is interesting

it's not correct though, i'm not entirely sure what it's calculating, but it's not what we want. possibly `multiply` was needed instead of `cross`? but that doesn't fix it. i'm not sure there's a way to reduce the problem to fewer than 3 conditionals, e.g.

```lua
function vector.in_area3(pos, v1, v2)
	local c = (pos - v1):multiply(v2 - pos)
	return c.x >= 0 and c.y >= 0 and c.z >= 0
end
```

but this isn't as clear and also isn't any faster when i test it.

2023-04-07 16:25 UTC, AFCMS commented
Added the unittests and renamed the function parameters.

2023-04-08 18:11 UTC, Desour requested changes

2023-04-08 18:11 UTC, Desour commented on games/devtest/mods/unittests/misc.lua
> +
Please put the unittest in `vector_spec.lua` (busted unittests).

2023-04-08 18:11 UTC, Desour commented on doc/lua_api.txt
> +	* Returns a boolean value indicating if `pos` is inside area formed by `min` and `max`.
Please rename to `in_area`, so that method syntax makes sense.

2023-04-08 18:11 UTC, Desour commented on doc/lua_api.txt
> +	* Returns a boolean value indicating if `pos` is inside area formed by `min` and `max`.
Please doc:
* min, max are inclusive.
* If min is smaller than max on some axis, function always returns false. (Could be worded better, idk.)

2023-04-08 22:43 UTC, Desour approved these changes
Looks good.

2023-04-10 13:37 UTC, rubenwardy commented on doc/lua_api.txt
> +	* If `min` is smaller than `max` on some axis, function always returns false.
I think you have these the wrong way around. min should be smaller than max.

I'd also mention `vector.sort`

2023-04-12 09:34 UTC, rubenwardy approved these changes

2023-04-12 09:46 UTC, merged