Add option to display reconnect on shutdown
minetest/minetest pull request #13433
Opened 2023-04-16 14:14 UTC by rdnuk

This PR optionally allows the reconnect button to show on the client when a server is restarted via a service manager.
Most service manager's use proper signalling which means Minetest shuts down normally and doesn't treat it as a crash.

This PR is a Ready for Review.

## How to test
Add `ask_reconnect_on_shutdown = true` in your server configuration file and then shutdown the Minetest server.

2023-05-14 10:43 UTC, SmallJoker commented
A vast majority of servers are up 24/7. Wouldn't it then make sense to default to true for dedicated server (i.e. non-"host game" instances)? I think that would be an easier solution for server owners to avoid further configuration steps.

2023-07-08 06:40 UTC, sfan5 requested changes

2023-07-08 06:40 UTC, sfan5 commented on builtin/settingtypes.txt
> +#    Whether to ask clients to reconnect after a shutdown request.
This isn't entirely accurate, a shutdown request from Lua can still choose to use a different value.

2023-07-08 06:40 UTC, sfan5 commented on src/server.cpp
> +			reconnect = g_settings->getBool("ask_reconnect_on_shutdown");
However this breaks some cases: If Lua doesn't set a shutdown message then its value for `reconnect` will always get overwritten.

2023-08-03 09:44 UTC, closed without merging