Add server favorite button
minetest/minetest pull request #13446
Opened 2023-04-19 21:03 UTC by PrairieAstronomer

This PR adds a button in the Join Game tab so that players can easily favorite servers without joining the server.

## To do

This PR is Ready for Review.

## How to test

Pull the branch, open the Join Game Tab, choose a server in the list of other servers, and click the star button. See that it adds the server to the favorites list. Make sure the unfavorite button still works and shows up correctly.

## Issues Fixed
This PR Fixes #12647.

2023-05-14 10:25 UTC, SmallJoker approved these changes
Works.

2023-05-26 18:42 UTC, nerzhul approved these changes
LGTM

2023-05-27 16:03 UTC, rubenwardy requested changes
Favouriting a server doesn't update the selection

https://github.com/minetest/minetest/assets/2122943/7903e641-ffe1-48eb-8374-b9d7f0b4c876

2023-06-18 16:08 UTC, Zughy commented
@PrairieAstronomer any updates? The PR is very close from getting merged

2023-07-13 03:16 UTC, closed without merging