Android: Remove Migration Code
minetest/minetest pull request #13590
Opened 2023-06-13 07:13 UTC by oong819

Add compact, short information about your PR for easier understanding:

- Goal of the PR
Remove Migration Code
- How does the PR work?
Remove Migtation Code
- Does it resolve any reported issue?
one (update soon)
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
not yet checked
- If not a bug fix, why is this PR needed? What usecases does it solve?
less permission, less less code

## To do

Ready for Review.

- [ ] test it

## How to test
0. open  Minetest
1. things should work fine

2023-06-13 14:41 UTC, oong819 commented
screwed up the code

2023-06-13 14:46 UTC, oong819 commented
un screwed up the code

2023-06-15 04:52 UTC, oong819 commented
i found  why its  failed, fixing

2023-06-18 05:33 UTC, oong819 commented
forgot a semicolon haha

2023-07-04 04:42 UTC, oong819 commented
ITS DONE REVIEW PLS?

2023-07-11 01:00 UTC, srifqi commented
As a note, 6901c5fae54eafb05494823b60d4e26c14b342f1 is added for the 5.5.0 release (31 January 2022). Any versions older than 5.5.0 needs to update first to any version from 5.5.0 until 5.7.0 for migrating the data files.

2023-07-11 01:00 UTC, srifqi requested changes
The concept and its implementation look good to me, except some code style issues.

2023-07-11 01:00 UTC, srifqi commented on android/app/src/main/java/net/minetest/minetest/MainActivity.java
```suggestion
```

2023-07-11 01:00 UTC, srifqi commented on android/app/src/main/java/net/minetest/minetest/MainActivity.java
```suggestion
```

2023-07-11 01:00 UTC, srifqi commented on android/app/src/main/res/values/strings.xml
I am not sure whether we want to remove empty lines here (see other XML files for examples).

2023-07-11 01:00 UTC, srifqi commented on android/app/src/main/java/net/minetest/minetest/MainActivity.java
>  	private void checkAppVersion() {
```suggestion

	private void checkAppVersion() {
```

2023-07-11 04:05 UTC, oong819 commented
done i think?

2023-07-12 12:40 UTC, srifqi requested changes
... just a little bit more.

2023-07-12 12:40 UTC, srifqi commented on android/app/src/main/java/net/minetest/minetest/MainActivity.java
There are some imports that can be removed.
```diff
diff --git a/android/app/src/main/java/net/minetest/minetest/MainActivity.java b/android/app/src/main/java/net/minetest/minetest/MainActivity.java
index 18475b2f8..d942e93e3 100644
--- a/android/app/src/main/java/net/minetest/minetest/MainActivity.java
+++ b/android/app/src/main/java/net/minetest/minetest/MainActivity.java
@@ -25,24 +25,14 @@ import android.content.Context;
 import android.content.Intent;
 import android.content.IntentFilter;
 import android.content.SharedPreferences;
-import android.content.pm.PackageManager;
-import android.os.Build;
 import android.os.Bundle;
-import android.os.Environment;
 import android.view.View;
 import android.widget.ProgressBar;
 import android.widget.TextView;
 import android.widget.Toast;

-import androidx.annotation.NonNull;
 import androidx.annotation.StringRes;
 import androidx.appcompat.app.AppCompatActivity;
-import androidx.core.app.ActivityCompat;
-import androidx.core.content.ContextCompat;
-
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.List;

 import static net.minetest.minetest.UnzipService.*;

```

2023-07-12 12:40 UTC, srifqi commented on android/app/src/main/java/net/minetest/minetest/UnzipService.java
There is an import that can be removed.
```diff
diff --git a/android/app/src/main/java/net/minetest/minetest/UnzipService.java b/android/app/src/main/java/net/minetest/minetest/UnzipService.java
index 83525a6c5..8c293fa89 100644
--- a/android/app/src/main/java/net/minetest/minetest/UnzipService.java
+++ b/android/app/src/main/java/net/minetest/minetest/UnzipService.java
@@ -28,7 +28,6 @@ import android.app.PendingIntent;
 import android.content.Context;
 import android.content.Intent;
 import android.os.Build;
-import android.os.Environment;
 import android.util.Log;

 import androidx.annotation.NonNull;

```

2023-07-14 07:00 UTC, srifqi approved these changes
This PR looks good to me.

2023-07-15 20:39 UTC, sfan5 approved these changes
Looks good too, but someone else should give it a quick test!

2023-07-17 13:36 UTC, grorp commented
I think these should be removed too:

https://github.com/minetest/minetest/blob/663c105eea90e99a99a3d115a80634ee3a777788/android/app/src/main/AndroidManifest.xml#L11-L15

https://github.com/minetest/minetest/blob/663c105eea90e99a99a3d115a80634ee3a777788/android/app/src/main/AndroidManifest.xml#L21

2023-07-18 12:14 UTC, oong819 commented
i wish Minetest ca export and import data files

2023-07-18 16:08 UTC, oong819 commented
merge pls?

2023-07-27 12:09 UTC, merged