Fix string conversion for FreeBSD
minetest/minetest pull request #13648
Opened 2023-07-07 18:01 UTC by nekobbbbbbit

Add compact, short information about your PR for easier understanding:

Fixes "<invalid UTF-8 string>" issue on FreeBSD.

I think it should work, dunno haven't tested it. But I'm certain it works.

2023-07-07 19:28 UTC, SmallJoker commented
Is `_SYSTYPE_BSD` defined on your side, by any chance? A general macro would also solve this issue for other BSD variants, if there is one in the first place.

2023-07-07 20:14 UTC, nekobbbbbbit commented
> Is `_SYSTYPE_BSD` defined on your side, by any chance? A general macro would also solve this issue for other BSD variants, if there is one in the first place.

I think it's probably safer to keep them separate. May also play poorly with macOS

2023-07-08 06:34 UTC, sfan5 requested changes

2023-07-08 06:34 UTC, sfan5 commented on src/util/string.cpp
> +#elif defined(__NetBSD__) || defined(__OpenBSD__) || defined(__FreeBSD__)
you need to modify the define on line 96 too

2023-07-08 15:17 UTC, nekobbbbbbit commented
Not sure that's needed, but fixed

2023-07-15 20:33 UTC, sfan5 approved these changes

2023-07-17 18:46 UTC, merged