Replace settings tab with button
minetest/minetest pull request #13762
Opened 2023-08-28 15:58 UTC by rubenwardy

# https://github.com/minetest/minetest/pull/13761 needs to be merged first

![image](https://github.com/minetest/minetest/assets/2122943/42fc735a-2811-47bc-907b-ea27cc8a7b9d)

## To do

This PR is a Work in Progress 

- [ ] Icon?

## How to test

Don't, please review https://github.com/minetest/minetest/pull/13761 first

2023-08-28 18:25 UTC, Zughy commented
Graphically speaking is pretty bad, the i con was more subtle. Icon + button, if any

2023-08-28 19:46 UTC, rubenwardy commented
This is still a draft PR - I was going to ask you for the icon again

2023-08-29 07:20 UTC, CallMeDax commented
I think an icon would be much better than a button, but the problem is that the art style wouldn't match the rest of the main menu. imo the tabs and other buttons should also be changed to have more of a pixel art style. possibly for a different PR. Also I think an icon is enough for the settings, since less text means less translations overflowing to the side.

2023-08-29 22:23 UTC, rubenwardy commented
Updated with icon provided by Zughy

2023-08-30 09:00 UTC, srifqi requested changes
Other than the bug on Windows, the PR looks good to me.

2023-08-30 09:02 UTC, grorp requested changes

2023-08-30 09:02 UTC, grorp commented on builtin/fstk/tabview.lua
> +	local end_button_size = 0.65
```suggestion
	local end_button_size = 0.75
```

The button is hard to hit on Android, I suggest increasing the size to `0.75`.

2023-08-30 09:02 UTC, grorp commented on builtin/fstk/tabview.lua
> +						self.width - end_button_size, -0.43 - end_button_size / 2,
```suggestion
						self.width - end_button_size,
						-tab_header_size.height / 2 - end_button_size / 2,
```

2023-09-07 12:00 UTC, srifqi approved these changes
Except a small change to the documentation, this PR looks good to me.

2023-09-07 15:31 UTC, grorp approved these changes

2023-09-09 16:49 UTC, merged