Document air_equivalent as deprecated
minetest/minetest pull request #13792
Opened 2023-09-11 18:16 UTC by sfan5

2023-09-12 01:49 UTC, erlehmann requested changes
If this is really deprecated, IMO the engine should warn in log every time this is accessed. After all, if you actually remove this property, something truthy may become falsy (nil).

”Unclear meaning” is not exactly correct, see: https://github.com/minetest/minetest/issues/13722#issuecomment-1714763808

2023-10-01 13:53 UTC, SmallJoker approved these changes

2023-10-02 11:44 UTC, merged

2023-10-02 12:30 UTC, erlehmann commented
Saying that it has an unclear meaning is still wrong, as discussed on IRC after I stopped a previous PR: https://github.com/minetest/minetest/pull/13790#issuecomment-1714288074

@SmallJoker what exactly changed since this was last discussio so that you approved it? What should people use *instead* of using air_equivalent? “Is this air or is this ignore” is most certainly not the correct replacement. I ask this for the 32 mods on ContentDB which use `air_equivalent`: https://web.archive.org/web/20230911164208if_/https://content.minetest.net/zipgrep/501df1d6-4355-4fd8-8afb-947ea023aa6e/

2023-10-02 19:09 UTC, SmallJoker commented
@erlehmann Node groups can be used to reflect such properties. Whether or not a node is air-like also depends on the interpretation. Air tanks might only consider breathable air variations as air-like (e.g. recharging air bottles), whereas machines might only care whether the node is some kind of non-explosive gas.