Move unsupported language list into a separate file
minetest/minetest pull request #13865
Opened 2023-10-03 17:00 UTC by srifqi

**Goal of the PR**
This PR tries to prevent compilation of unsupported languages on Android build (fixes #13808).
~This PR tries to add better handling for unsupported languages (fixes #13808).~ _(see replies below)_

**How does the PR work?**
- Move unsupported language list into a separate file. Both build scripts now read from that file.
- ~Add unsupported language list in the `build.gradle`~ _(see replies below)_
- ~Add more checks when initialising language for Gettext~ _(see replies below)_

**Does it resolve any reported issue?**
Yes, #13808.

**Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?**
The reported issue is in the 5.8.0 milestone.

## To do

This PR is Ready for Review.

## How to test

1. Set system language to be any language in the unsupported language list.
2. Run Minetest.
3. Make sure that the shown language is in English.
4. Retry step 1 to 3, but using (a) `language` setting in `minetest.conf` and (b) environment variables (`LANG` or `LANGUAGE`).

## Notes

Implementation (code) suggestions are welcome. I just tried to piece together some code that might/might not work for all operating system. I have tested this PR in Windows 10 and Android 13.

Some suggest to only change the build steps so that unsupported languages are never selected (because they do not exist). If that is the better case, any changes to `src/gettext.(cpp|h)` can be canceled.

2023-10-03 17:21 UTC, sfan5 commented
> Some suggest to only change the build steps so that unsupported languages are never selected (because they do not exist). If that is the better case, any changes to src/gettext.(cpp|h) can be canceled.

This would definitely be better and as far as I can see you have already done that with your changes to build.gradle.

2023-10-04 08:00 UTC, srifqi commented
All right, I have reverted changes in `src/gettext.(cpp|h)`.

-------

Note when doing squash and merge: The commit message should be
```
Add unsupported language list into app/build.gradle
```

2023-10-04 08:52 UTC, grorp requested changes
Worked after I cleaned my build cache.

That the list of unsupported locales now appears in two different places is unfortunate, but it's probably difficult to do this better.

2023-10-04 08:52 UTC, grorp commented on android/app/build.gradle
> +	// List of languages that are not supported. See issue #4638.
```suggestion
	// List of languages that are not supported. See issue #4638.
	// Must be kept in sync with "GETTEXT_BLACKLISTED_LOCALES" in "src/CMakeLists.txt".
```

Please add a similar comment to `src/CMakeLists.txt`:

```
# Must be kept in sync with "unsupportedLanguages" in "android/app/build.gradle".
```

2023-10-04 11:14 UTC, grorp approved these changes

2023-10-04 14:20 UTC, srifqi commented
Since the translation compilation is run by two different scripts, we can put unsupported language list in a separate file and read the file in the build scripts.

`src/unsupported_language_list.txt`
```
List of languages that are not supported. See issue #4638.
ar
dv
he
hi
kn
ms_Arab
th
```

`src/CMakeLists.txt`

```CMake
FILE(READ "${CMAKE_SOURCE_DIR}/src/unsupported_language_list.txt" GETTEXT_BLACKLISTED_LOCALES)
STRING(REGEX REPLACE "\n" ";" GETTEXT_BLACKLISTED_LOCALES "${GETTEXT_BLACKLISTED_LOCALES}")
```

`android/app/build.gradle`

```Gradle
def unsupportedLanguages = new File("${projRoot}/src/unsupported_language_list.txt").text.readLines()
```

2023-10-05 15:13 UTC, sfan5 approved these changes
lgtm

2023-10-05 15:29 UTC, merged