Prevent key_up and key_down events from respawning the player in the death screen
minetest/minetest pull request #13870
Opened 2023-10-05 23:00 UTC by srifqi

**Goal of the PR**
This PR tries to prevent early respawns caused by up/down button.

**How does the PR work?**
This PR prevents `key_up` and `key_down` events from respawning the player in the death screen.

**Does it resolve any reported issue?**
Yes, this PR tries to fix #13863.

**Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?**
The reported issue is in the 5.8.0 milestone.

## To do

This PR is Ready for Review.

## How to test

1. Make the player's character die inside a Minetest world.
2. Press <kbd>↑</kbd>/<kbd>↓</kbd> (up/down button) when the "You died" dialog (death screen) is being shown.
3. Nothing should occur.

2023-10-07 09:05 UTC, SmallJoker commented
Shouldn't the respawn only be triggered when pressing the "Respawn" button or closing the formspec?

2023-10-07 18:00 UTC, srifqi commented
> Shouldn't the respawn only be triggered when pressing the "Respawn" button or closing the formspec?

That is what this PR tries to fix.

> EDIT: I cannot reproduce this issue on Ubuntu 22.04. Only space, escape and mouse clicks trigger the respawn.

I can reproduce the issue using the recent `master` branch/5.7.0 on Lubuntu 22.04.3 LTS (both in a virtual machine and by using dual-boot).

2023-10-08 14:29 UTC, grorp requested changes
I can reproduce the bug. This fix works, but I'd prefer a positive condition instead of a negative one, i.e. something like this:

```cpp
if (m_formname == "MT_DEATH_SCREEN") {
	assert(m_client != nullptr);

	if (fields.find("quit") != fields.end())
		m_client->sendRespawn();

	return;
}
```

That would make the code more self-explanatory (the comment wouldn't be necessary) and more future-proof. (I've tested that "quit" covers all cases where respawning should be triggered.)

2023-10-09 10:00 UTC, srifqi commented
Thank you for the test.

> I've tested that "quit" covers all cases where respawning should be triggered.

That's true because even the button uses `button_exit[]` element (produces "quit" field):

```cpp
"button_exit[4,3;3,0.5;btn_respawn;" + gettext("Respawn") + "]"
```

> Special case: `["quit"]="true"` is sent when the user actively closed the form by mouse click, keypress, or through a `button_exit[]` element.

2023-10-09 13:34 UTC, grorp approved these changes

2023-10-09 15:13 UTC, merged