Add help formspec for CSM commands
minetest/minetest pull request #13937
Opened 2023-10-27 15:57 UTC by zmv7

This PR adds graphical interface for `.help` command, the similar as used on the server (`/help`).

## How to test

* Set `enable_client_modding` to `true` in minetest.conf
* Install some client mods (optional)
* Join singleplayer or any server that allows to load client mods
* Type `.help` in the chat and test the functionality of formspec.
* `.help -t` and `.help all -t` should return output to the chat without using formspec

2024-01-22 17:36 UTC, appgurueu requested changes
This looks like it duplicates existing help formspec code. Can't that be moved to `builtin/common/information_formspecs.lua`?

2024-01-23 05:52 UTC, zmv7 commented
Here we go, now there is universal function for both server and client help formspecs in information_formspecs.lua

2024-01-24 15:56 UTC, appgurueu commented on builtin/common/information_formspecs.lua
> +	if INIT == "client" then
Is this change necessary?

2024-01-24 17:19 UTC, appgurueu approved these changes
Looks fine, works.

2024-02-02 21:13 UTC, merged