Add Esperanto builtin translation
minetest/minetest pull request #14215
Opened 2024-01-04 23:31 UTC by JadedCtrl

Short and sweet: Adds an Esperanto translation for the “builtin” mod.

Cheers! :)

2024-01-17 23:00 UTC, srifqi requested changes
There are some issues.

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> + (@1 s)=
This has not been translated. Even if it is the same, please also write it.

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> +@1 @= @2=
This has not been translated. Even if it is the same, please also write it.

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> +@1 spawned.=@2 naskiĝis.
Did you mean `@1`?
```suggestion
@1 spawned.=@1 naskiĝis.
```

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> +[<0..23>:<0..59> | <0..24000>]=
This has not been translated. Even if it is the same, please also write it.

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> +[full | quick]=
This has not been translated. Even if it is the same, please also write it.

2024-01-17 23:00 UTC, srifqi commented on builtin/locale/__builtin.eo.tr
> +Clearing all objects. This may take a long time. You may experience a timeout. (by @1)=Forigante ĉiun lasitan portaĵon. Tio ĉi eble postulos longan tempon. Vi eble malkonektiĝos pro tempo-elĉerpo.
The text "(by `@1`)" has not been translated.

2024-01-18 17:55 UTC, JadedCtrl commented
Thanks for the fixes, @srifqi! Just force-pushed them. :)

2024-01-20 14:36 UTC, merged