Expose Sha224 & Sha256 algorithms to lua api
minetest/minetest pull request #14259
Opened 2024-01-14 18:43 UTC by chmodsayshello

This is a pull request allowing the sha224 and sha225 algorithms that already are in minetest's code to be used by mods, which are currently limited to just sha1. This allows mods to hash a given set of data in a more secure way if needed.

Since both functions would be identical, with only the SHA224/256 being the difference, I used a function pointer to avoid code duplication.

- Goal of the PR
- How does the PR work?
- Does it resolve any reported issue?
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
- If not a bug fix, why is this PR needed? What usecases does it solve?

**This PR Ready for Review.**
## How to test

1. Clone my branch and compile minetest
2. Call minetest.sha224 and minetest.sha256 as a mod, and log the result
3. Use an external tool/webpage [like this](https://emn178.github.io/online-tools/) to verify the hash is correct.

2024-01-14 20:55 UTC, wsor4035 commented
just a thought as a modder/thinking of the api, as these options are added, potentially more in the future, it seems this would pollute to a degree the minetest api namespace, maybe it would be better to have something like `minetest.encode(method, ...)` similar to `minetest.compress`? with the previous said, of course `minetest.sha1` will have to exist for backwards compat, however that could be depreciated and aliased to a new function.

alternatively:
`minetest.encode.TYPE`

2024-01-14 21:14 UTC, appgurueu commented
> just a thought as a modder/thinking of the api, as these options are added, potentially more in the future, it seems this would pollute to a degree the minetest api namespace, maybe it would be better to have something like `minetest.encode(method, ...)` similar to `minetest.compress`? with the previous said, of course `minetest.sha1` will have to exist for backwards compat, however that could be depreciated and aliased to a new function.
> 
> alternatively: `minetest.encode.TYPE`

The latter is the better suggestion, IMO.

* It means `minetest.hash.this_does_not_exist(...)` will result in an attempt to call a `nil` value (otherwise we'd have to implement erroring on invalid values ourselves).
* Modders can also check for the existence of a certain method conveniently - just `minetest.hash.method` (otherwise we'd have to add some feature flags or similar).
* Editor tooling will also understand `minetest.hash.blah` better than `minetest.hash("blah", ...)`.
* It also makes the intent (we're choosing an *algorithm* here, not passing some string data) clearer, IMO.

(By the way, it should be `minetest.hash` or similar. These are "secure hashing" algorithms.)

2024-01-14 22:28 UTC, sfan5 commented
IMO there's no reason or usecase for sha224 and we shouldn't expose it. If we have leftover code we should rather go and remove it.

2024-01-14 22:33 UTC, wsor4035 commented
> The latter is the better suggestion, IMO.
> 
> * It means `minetest.hash.this_does_not_exist(...)` will result in an attempt to call a `nil` value (otherwise we'd have to implement erroring on invalid values ourselves).
> * Modders can also check for the existence of a certain method conveniently - just `minetest.hash.method` (otherwise we'd have to add some feature flags or similar).
> * Editor tooling will also understand `minetest.hash.blah` better than `minetest.hash("blah", ...)`.
> * It also makes the intent (we're choosing an _algorithm_ here, not passing some string data) clearer, IMO.
> 
> (By the way, it should be `minetest.hash` or similar. These are "secure hashing" algorithms.)

while i agree, mainly suggested it that way to keep consistency with `minetest.compress`

2024-01-17 17:09 UTC, chmodsayshello commented
I'll add #14265 as a dependency as it's likely to be merged before this, and that way I'll be able to update the PR for it early...

2024-01-19 12:14 UTC, Zughy commented
@chmodsayshello the PR you mentioned has been merged, feel free to proceed as discussed :)

2024-01-27 19:34 UTC, sfan5 requested changes

2024-01-27 19:34 UTC, sfan5 commented on src/script/lua_api/l_util.cpp
> +	data_sha256.assign((char *) SHA256((const unsigned char*) data, size, NULL), SHA256_DIGEST_LENGTH);
> If md is NULL, the digest is placed
       in a static array. Note: setting md to NULL is not thread safe.

2024-01-27 19:34 UTC, sfan5 commented on src/script/lua_api/l_util.h
> -
please keep this space

2024-02-21 20:24 UTC, closed without merging