Add per-node climb speed modifier (try 2)
minetest/minetest pull request #14267
Opened 2024-01-17 15:04 UTC by Wuzzy2

This fixes #1935.

This adds climb_factor property to nodes. It's a float that modifies the climbing speed on climbable nodes.

## How to test

* Use the new climbable nodes in DevTest. There's a fast, slow and normal one. Compare the speeds.
* Combine this with a custom player physics override `speed_climb` (via `player:set_physics_override`)

## Limitation

Anticheat is *not* tested!

2024-06-03 17:45 UTC, Zughy commented
@Wuzzy2 rebase needed

2024-06-04 17:46 UTC, Wuzzy2 commented
Done!

2024-08-13 19:04 UTC, sfence requested changes
Looks well. Tested without issue. Only code style issue found.

2024-08-13 19:04 UTC, sfence commented on games/devtest/mods/testnodes/properties.lua
> +	tiles = {"testnodes_climbable_top.png^[colorize:#FFFFFF:140","testnodes_climbable_top.png^[colorize:#FFFFFF:140","testnodes_climbable_side.png^[colorize:#FFFFFF:140"},
```suggestion
	tiles = {
		"testnodes_climbable_top.png^[colorize:#FFFFFF:140",
		"testnodes_climbable_top.png^[colorize:#FFFFFF:140",
		"testnodes_climbable_side.png^[colorize:#FFFFFF:140"
	},
```

We want lines to be wrapped at 80 characters.

2024-08-13 19:04 UTC, sfence commented on games/devtest/mods/testnodes/properties.lua
> +	tiles = {"testnodes_climbable_top.png^[colorize:#000000:140","testnodes_climbable_top.png^[colorize:#000000:140","testnodes_climbable_side.png^[colorize:#000000:140"},
```suggestion
	tiles = {
		"testnodes_climbable_top.png^[colorize:#000000:140",
		"testnodes_climbable_top.png^[colorize:#000000:140",
		"testnodes_climbable_side.png^[colorize:#000000:140"
	},
```

2024-08-16 22:30 UTC, appgurueu commented on doc/lua_api.md
> +    -- change the setting "movement_speed_climb".
Isn't it a bad idea to advise modders to change settings when they have no proper way to reset them? Why not advise them to use the physics override instead?

(That said, movement probably shouldn't be controlled by such settings...)

2024-08-16 22:30 UTC, appgurueu commented on games/devtest/mods/testnodes/properties.lua
> +
What's with these blank lines (same below)?

2024-08-18 09:36 UTC, Wuzzy2 commented
I agree, the wording for the climb setting was too suggestive, so I rephrased it in a more neutral way without making recommendations. I still don't want to recommend *against* using settings in games; games often use a game-specific `minetest.conf` file. This is safer as it doesn't edit the global `minetest.conf` like `minetest.settings:set()` would.

The two blank lines actually have a reason. Back when I did the major DevTest rewrite a few years ago, I decided on a style that node definitions have the things that are relevant for the test at the top, and the less relevant boilerplate stuff is at the bottom, separated by two blank lines. This is explicitly mentioned in `testnodes/drawtypes.lua`.

2024-08-18 10:07 UTC, sfence approved these changes

2024-08-28 11:17 UTC, Desour reviewed
Wouldn't it make sense to have separate up and down climb speed modifiers?

---

Idk if anticheat is an issue. I'll leave somebody else to judge.

2024-08-28 11:17 UTC, Desour commented on src/client/localplayer.cpp
> +			node_climb_factor = nodemgr->get(node.getContent()).climb_factor;
Shouldn't this consider `node2`?

2024-08-28 11:17 UTC, Desour commented on src/nodedef.cpp
> +	climb_factor = 1.0;
```suggestion
	climb_factor = 1.0f;
```

2024-08-28 11:17 UTC, Desour commented on games/devtest/mods/testnodes/properties.lua
> +
Unresolved. Double new line still there.

2024-08-28 11:17 UTC, Desour commented on doc/lua_api.md
> +    -- climbable.
up,down and s/with/by/
```suggestion
    -- The speed at which a climbable node can be climbed up and down
    -- is multiplied by this number. Must not be negative. No effect if
    -- node isn't climbable.
```

Might also be worth noting here that climb speed depends on horizontal walking speed.

2024-08-28 18:07 UTC, grorp commented on doc/lua_api.md
> +    -- `movement_speed_climb`.
should also mention the physics override, e.g. like this:

```suggestion
    -- Note: The base climbing speed is controlled by the setting
    -- `movement_speed_climb` multiplied by the physics override `speed_climb`.
```

2024-08-29 17:33 UTC, appgurueu commented
I do think anticheat is probably somewhat of an issue here, especially with "extreme" values (> 2), though if a few other variables are increased as well, they can "make up for it" - relevant code:

https://github.com/minetest/minetest/blob/master/src/server/player_sao.cpp#L660-L714

A simple solution might be to multiply the climb factor by the max climb speed of any node. A more sophisticated solution would only take into account nodes next to the player. Just disabling the check for upwards movement is also an option. (I think that our anticheat code probably is already broken in many more complex cases.)

2024-08-29 17:58 UTC, sfence commented
An idea... what about a separate climb speed factor for climbing up and down?

For example, a fireman pole can use it: https://c7.alamy.com/comp/CW440H/fire-station-protective-clothing-and-pole-CW440H.jpg
Quick down, slow up.
Similar for ropes etc.

2024-10-26 16:37 UTC, Wuzzy2 commented
@appgurueu: Scanning every node definition first just for one anticheat check doesn't sound efficient, not sure about that.
I have a different idea. What about putting a hardcoded upper limit for climb speed modifier. Like 10 or 5, idk. And use the same number in anticheat. Obvious downside is that anti cheat is now much more tolerant to high Y speeds, but at least it doesn't trigger false-positives (which is more critical IMO).

@sfence: That's out of scope. First I need to get the per-node climb speed working.

2024-10-26 16:39 UTC, Wuzzy2 commented
> Shouldn't this consider node2?

@Desour: Normal node seems to work for me. The difference between `node` and `node2` is a small Y offset. I think taking the climb speed of either node is reasonable.

2024-10-26 18:51 UTC, Desour commented
> > Shouldn't this consider node2?
> 
> @Desour: Normal node seems to work for me. The difference between `node` and `node2` is a small Y offset. I think taking the climb speed of either node is reasonable.

But the `is_climbing` above uses node2. It is possible that `node` isn't even climbable.

2024-10-27 11:21 UTC, Wuzzy2 commented
OK, I reconsidered. I tested it and there was a small section below a hanging climbable node where default climb speed always applies. Yeah, this is less than ideal.

This is how it works now: The game looks at node directly at the player pos and node2, which is offset by -0.2 on the Y axis from the first node. The player is climbing while inside *either* of those nodes. I suppose this was done so the player can still climb slightly above a climbable node. (so far, nothing new)

Now the new climb speed rule is to take the `climb_factor` of the lowest of the two nodes that is climbable, i.e. either node2 or node. That way *some* `climb_factor` is guaranteed to be used, if one exists.

I playtested this and this behavior indeed makes more sense to me. Feel free to playtest this in DevTest as well.

I'm still waiting for an answer on what to do to fix anticheat. Would a hardcoded upper limit for `climb_factor` (like I explained above) be OK?

2024-12-23 11:37 UTC, sfan5 commented
rebase needed and @appgurueu maybe you have time to review it soon?

2024-12-23 13:33 UTC, Wuzzy2 commented
Rebase completed. My own quick test was successful.

2024-12-26 09:38 UTC, SmallJoker reviewed
Works. Stylistic change requests only.

2024-12-26 09:38 UTC, SmallJoker commented on doc/lua_api.md
> +
Please move below  `climbable` (a few lines up).

2024-12-26 09:38 UTC, SmallJoker commented on src/client/localplayer.cpp
> +		}
Slightly shorter code, where `node` and `node2` are only used once, hence reduces potential confusions about which one's the upper or lower node.
```suggestion
		const ContentFeatures &cf_upper = nodemgr->get(node.getContent());
		const ContentFeatures &cf_lower = nodemgr->get(node2.getContent());
		is_climbing = (cf_upper.climbable || cf_lower.climbable) && !free_move;
		if (is_climbing) {
			node_climb_factor = cf_lower.climbable
				? cf_lower.climb_factor : cf_upper.climb_factor;
		}
```

2024-12-26 09:38 UTC, SmallJoker commented on src/nodedef.cpp
> +	} catch(SerializationError &e) {};
```suggestion
	} catch (SerializationError &e) {}
```

2024-12-26 09:38 UTC, SmallJoker commented on src/script/common/c_content.cpp
> +	getfloatfield(L, index, "climb_factor", f.climb_factor);
Please move below `getboolfield(L, index, "climbable", f.climbable);` (above).

2024-12-26 09:38 UTC, SmallJoker commented on src/nodedef.cpp
> +	climb_factor = 1.0f;
Please move this below `climbable` or move the initialization to `nodedef.h` (L391).

2024-12-26 11:03 UTC, SmallJoker commented
> Anticheat is not tested!

Patch: [0001-Anticheat-respect-climb_factor.patch.zip](https://github.com/user-attachments/files/18252222/0001-Anticheat-respect-climb_factor.patch.zip)

In order to test this:

1. Change `if (0)` in `checkMovementCheat` to ìf (1)`
2. Compile
3. Start a local server
4. `/revokeme fast`
5. Build a very high pillar of `testnodes:climbable_fast`
6. Climb up.
8. Teleport back to the bottom of the pillar and climb up as fast as possible again.

Observe the logged remainder value (higher = safe, zero = anticheat trips). With this change, the remainder should generally stay at the maximum (5).

2024-12-28 15:44 UTC, Wuzzy2 commented
OK, I did the requested changes (not anticheat). Question: Is it safe to just move the `getfloatfield` around like arbitrarily? I thought the order of these functions is important. (I didn't look too closely.)

As for anticheat, your patch does not work as promised. When I follow the instructions, the remainder quickly drops below 5. The minimum value I was able to get was 0.1.

2024-12-28 21:46 UTC, SmallJoker commented
> Question: Is it safe to just move the `getfloatfield` around like arbitrarily?

Depends on which Lua table that's currently operated on. Here it's the main NodeDef table for both code sections mentioned in https://github.com/minetest/minetest/pull/14267/files/e3aa419695f293d4620a3ccda5cb0eb52e7faccd#diff-d573872189d9a658569afa1674db8f099ad59bf8599d3f1d3ebb99040969dd2b. Hence, the getter function may be moved.

> When I follow the instructions, the remainder quickly drops below 5.

I see. Teleporting does reset this value, which might be what you're seeing. Simply climbing up the pillar (image below) should not permanently decrease the logged remainder. So if the remainder does not reach zero, we should be fine.

![test_setup](https://github.com/user-attachments/assets/b28201ed-6966-4cb9-91de-f560f76ff1ee)

2025-03-29 15:34 UTC, Wuzzy2 commented
It’s been a long time. I’m wondering if there is anything that is blocking this PR besides (probably) "rebased needed" and "anticheat" (or is that not a blocker?).

2025-03-29 16:53 UTC, SmallJoker commented
No rebase needed yet. Hence only the anticheat topic remains.

2025-09-07 18:46 UTC, sfan5 commented
Please implement that, or we can't merge this PR.

2025-11-10 11:07 UTC, closed without merging