Add repeat_dig_time setting
minetest/minetest pull request #14295
Opened 2024-01-21 16:02 UTC by ryvnf

#### Goal of the PR

Provide better accessibility for people who accidentally dig instant breakable nodes but want dig repetition and cannot use the `safe_dig_and_place` setting.

This PR solves this problem by introducing a `repeat_dig_interval` which is like `repeat_place_interval` but for digging. The setting simply ensures that it will take at minimum the settings value from finishing digging one node to starting to dig the next node.

#### Does it resolve any reported issue?

Yes, #13726.

## To do

This PR is ready to review.

## How to test

Hop into a world and hold the dig button on nodes which are instant breakable. Could be done by hopping into a creative world in Mineclonia and start digging any nodes.

Try it with the default value and verify that the digging speed remains the same as previously. Then go into the settings menu and update the _Dig repetition interval_ setting to a higher value. Hop into the world again and dig nodes, verify that there is a larger delay between digging each node.

## Things to consider

The range of values allowed is probably something which should be discussed. Previously, the hardcoded value was 0.15. Currently I made the minimum setting value 0.15 and the maximum 2.0 with the default being 0.15.

The `repeat_place_interval` is minimum 0.16 and maximum 2.0. It could be argued that maybe its minimum value should be lowered to 0.15 for consistency with the `repeat_dig_interval` setting.

But perhaps the minimum value of `repeat_dig_inverval` could be lower?

2024-01-29 16:29 UTC, grorp requested changes
> Try it with the default value and verify that the digging speed remains the same as previously.

The existing minimum value of `0.15` for `runData.nodig_delay_timer` only applies for nodes that take zero time to dig. There can be lower values in other cases:

- In Minetest Game creative mode, the most common value seems to be `0.0328125`.
- When digging dirt in Minetest Game without creative mode, the value is `0.14`.

This means that this PR actually (by default) results in a lower digging speed in some cases. To preserve the existing behavior, the default value for `repeat_dig_time` should be `0.0`.

2024-01-29 16:32 UTC, grorp commented on builtin/settingtypes.txt
> +repeat_dig_time (Dig repetition interval) float 0.15 0.15 2
```suggestion
#    The minimum time in seconds it takes between repeated node digging when
#    holding the dig button.
repeat_dig_time (Dig repetition interval) float 0.15 0.15 2.0
```

This setting works (and is very useful!) on touchscreen devices too.

2024-02-24 11:37 UTC, grorp reviewed
Tested a bit, seems good.

I'm not sure what to think of the change to the minimum of `repeat_dig_time`, but it probably won't make a big difference.

2024-02-24 11:37 UTC, grorp commented on minetest.conf.example
> +
No need to update minetest.conf.example, it'll be regenerated before release.

2024-02-24 11:37 UTC, grorp commented on src/client/game.cpp
> +	m_repeat_place_time                  = g_settings->getFloat("repeat_place_time", 0.15f, 2.0f);
I suppose `repeat_dig_time` be cached here too.

2024-03-05 22:20 UTC, grorp requested changes
Calls to `g_settings->(de)registerChangedCallback` are missing for the new setting.

2024-03-06 20:40 UTC, grorp approved these changes

2024-03-30 10:05 UTC, merged

2024-06-23 22:11 UTC, AsumFace commented
Hi,
we have intentionally extremely fast tools on the servers Tunnelers' Abyss and Centeria and this change is breaking them due to the imposed minimum duration of 0.15 s. We do no see any necessity for breakage and suggest lowering the minimum to 0 in order not to break games that are relying on it.

2024-06-24 14:34 UTC, Desour commented
> Hi, we have intentionally extremely fast tools on the servers Tunnelers' Abyss and Centeria and this change is breaking them due to the imposed minimum duration of 0.15 s. We do no see any necessity for breakage and suggest lowering the minimum to 0 in order not to break games that are relying on it.

IIRC, I tested this because I thought this would be an issue. I've used the devtest `basetools:pick_mese` for this. But I couldn't reach instantaneously fast dig times, and concluded it was already broken before the PR, and hence I remained silent.
It's also very possible that I tested wrongly. I'd like to see reproduction steps.
If there's a regression, please open an issue.

2024-06-24 17:07 UTC, superfloh247 commented
Hard to measure this correctly, but since this is merge into main the 5.9.dev latest master the alien tools pick axe on Wunderwelt feels slower.
I manually patched my client to allow a minimum of 0.025 and the alien tools pick axe feels normal again.

How to measure this properly?