[NO SQUASH] Add hypertext support to tooltips
minetest/minetest pull request #14728
Opened 2024-06-04 21:28 UTC by Wuzzy2

### Background of this PR

I was asked by @kilbith to submit this PR, who did the work for the first commit. @kilbith is unable to do it alone because of a ban. I have looked at the new feature and tested it myself, checked the code and it looks OK. I believe it will be like a very good addition to Minetest, but it needs work. Please read the code carefully yourself before running it.

I do not know if our policies allow a PR to be made like this. If you dislike what I try to do here, I feel very sorry. Just close this PR and it's over. But if this is OK:

We have explicit, written permission to use this work under LGPLv2.1+. Quote from e-mail conversation with @kilbith:

> 1. Permission is expressly granted by my organization to license this code
> under the GNU LGPL v2.1+ terms.

This e-mail has been cc'ed to @celeron55 as well.

**IMPORTANT: DO NOT SQUASH!** The first commit MUST be left unaltered, which contains the requested author identity. I was given the patch only under this condition, to which I agreed. The agreement allows to *add* new commits to build on the initial commit tho. So bugfixes and changes all have to go in NEW commits.

### Feature description

This feature will add hypertext support for tooltips by introducing a new `supertip` tooltip element. This element works like `tooltip` but you can write hypertext (like for the `hypertext` element).

There are two modes: dynamic and static. Dynamic supertips will show up next to the cursor, just like normal ones. Static supertips appear at a fixed formspec coordinate.

Also, supertips can be *styled*.

See the `lua_api.md` for details.

The documentation currently declares the `posX, posY` to be optional. This does NOT mean you can leave the field empty. Instead, the field is skipped entirely if skipped. I believe this goes against Minetest conventions. Feel free to discuss a better syntax for this formspec element.

### Demo

Here is a video demonstration:

https://www.youtube.com/watch?v=RAASW_Rj8eQ

In the 2nd commit, I have added a simple text/example in DevTest in the `/testformspec` command (new "Tooltip" tab).

### Known bugs

This PR is a DRAFT. Expect more commits to come.

There are various known bugs at the moment:

* SEGFAULT if a mod makes a syntax error in a supertip (like a wrong argument count)
* Dynamic supertips may appear FAR away from the cursor, even out of window (depends on window size)
* At small window sizes, the text of a supertip might be cut off
* When you hover a supertip the first time, it can be very large for a split second (may need multiple tries to reproduce)

@kilbith has suggested that no further work on this can be expected. This means it's now up to me to fix the rest. Help is appreciated.

### Feedback

This PR is a draft, but feedback of the concept is greatly appreciated. Especially please comment on the syntax and design choices. I think the way how the `posX,posY` argument is made optional should probably also be changed (discuss).

Also report any bugs I didn't find myself before.

2024-06-05 12:27 UTC, nerzhul commented
it sounds to be a very good enhancement.
A question about this, cannot we just have our current tip code using this new parsing method ?
Is supertip the good name ? 
If it's a new UI addition, don't we need a protocol bump ? what happen if a server uses it and the client is older ?

2024-06-05 12:28 UTC, nerzhul commented on src/gui/guiFormSpecMenu.cpp
> +		X = m_pointer.X - 1120;
what should be do with this ?

2024-06-05 12:31 UTC, nerzhul commented
another comment, can we have multiple examples in devtest ?

2024-06-05 12:46 UTC, Wuzzy2 commented
Well, all these things are open for debate. I haven't deeply analyzed the code myself yet, only read it twice. The only thing that matters is that the 1st commit remains intact.

I agree that `supertip` might not be the ideal name, but I'm neutral about this. I don't know why @kilbith chose to add a new formspec element rather than extending `tooltip`. But I can think of some reasons myself: Keeping the default tooltip simple and for compability. Also, please keep in mind that the `supertip` syntax will parse hypertext, so `<` and `>` have a special meaning. While the default `tooltip` does not give them special treatment. We cannot make `tooltip` suddenly parse hypertext, it will break tooltips that already use `<` and `>` and other special characters as plain text.

Although a new param could be added to toggle hypertext parsing. And it is off by default.

supertip does other things as well: It is also stylable and allows absolute positions.

But yeah, thinking about it, it MAY be possible to extend the `tooltip` element instead, the hard part is to make sure it'll all be backwards-compatible and not making the new syntax too messy. Annoyingly, for this to work, I'm afraid we'd have to add the new parameters *after* the text. But as long it works …

Another open question is whether this will require a new formspec version. I don't the rules for that.

As I understand the code, it does not currently handle the case of an old client receiving a supertip. This was not tested yet, so assume the worst. :D

Anyway. I think the top priority for me is to fix all the bugs first to get it to work properly. Optimization/cleanup can come later.

2024-06-05 12:53 UTC, Wuzzy2 commented
There *are* multiple exampels in DevTest, in the `/test_formspec` command. Or did you mean the current examples are not enough? If so, I agree. Adding more DevTest examples is on my TODO list. Currently missing is an example for styling.

About this code:

> /* Issue with floating tooltips' positioning here.
> Set hardcoded values that only works on 16:10/4K displays. */

@kilbith told me this is a workaround for a known bug, to "force" the feature to work *at all*. The bug here is that the supertip is not positioned correctly if it's dynamic. It is often placed far away from the cursor, changing with screen size. So what needs to be done is to fix the bug, making sure dynamic supertips appear correctly at the cursor. (dynamic supertip = tooltip that appears relative to the cursor, like the default tooltip)

2024-06-05 12:55 UTC, nerzhul commented
for the devtest part, ignore my comment, i just skipped the file in my brain, it's ok :D

2024-06-06 12:36 UTC, Wuzzy2 commented
Progress report: Dynamic supertips (i.e. supertips that follow the cursor like normal tooltips) now have the correct positioning. I also changed the syntax. The `posX,posY` argument is now called `staticPos` and is mandatory, meaning the element now has a fixed argument count. This should make things clearer and easier to understand. I also fixed a segfault when this argument had invalid syntax.

2 known bugs remain (see above).

> for the exteneded parsing, we can imagine extended=true attribute in tooltip directly, switching the parsing mode maybe ?

Yeah, I was thinking about something like thit. I could probably work, I just need to figure out the proper syntax while maintaining compat.

2024-06-06 15:21 UTC, grorp reviewed
Thoughts:

- "hypertext + tooltip = supertip"? Not rather "hypertip"?

- I feel like having a new element for hypertext tooltips, instead of reusing the existing tooltip element by adding new parameters at the end, is less confusing. There's also the `fontcolor` and `bgcolor` parameters for regular tooltips, which wouldn't make much sense for hypertext tooltips.

- Compared to regular tooltips, hypertext tooltips seem to miss the feature where you can "attach" them to formspec elements. It might make sense to support this for consistency.

- Not required in this PR, but I think it would be great if item (metadata) tooltips could also optionally use hypertext.

2024-06-06 16:37 UTC, rubenwardy commented
I recommend the obvious name: `tooltip_hypertext`

2024-06-11 18:53 UTC, nerzhul requested changes

2024-06-11 18:53 UTC, nerzhul commented on src/gui/guiHyperText.cpp
> +		m_drawer.draw(AbsoluteClippingRect,
please add braces, it's a very dangerous 2 lines no braces notation

2024-06-11 18:53 UTC, nerzhul commented on src/gui/guiHyperText.h
> +	ParsedText &getText() { return m_text; }
i don't like this very dangerous pattern, it's better to have a copy and a setting i think. ok it's optimized memory side, but having full access to a member ref sounds bad

2024-06-28 18:45 UTC, nerzhul requested changes, later dismissed

2024-06-28 18:45 UTC, nerzhul commented on src/gui/guiFormSpecMenu.cpp
> +	} else {
useless else, just return on the previous braces and remove this else braces

2024-06-28 18:45 UTC, nerzhul commented
appart some style it sounds good, anything remaining to fix to move out of draft ?

2024-06-29 10:23 UTC, Wuzzy2 commented
The one remaining bug is that the tooltip width is too small and may even make its content disappear when the window is small.
Currently, tooltip width is relative to formspec units but I think this is the wrong approach. I think it is better is to use typographic em units.

I agree the `&getText` is indeed risky and should be replaced; I haven’t gotten a replacement to work so far and haven’t made another try at this.

2024-08-16 05:23 UTC, Wuzzy2 commented
The reason why there has been no progress recently is because I'm stuck and don't know how to fix the remaining bugs/issues. :-(

Sorry.

2024-08-18 11:14 UTC, Wuzzy2 commented
I'm happy to report that kilbith fixed the `&getText` issue and I decided to move this PR out of draft.

Now the only bug is the tooltip width issue, as explained in <https://github.com/minetest/minetest/pull/14728#issuecomment-2198091438>.

I think this is a serious issue that should not be ignored. Nowhere else does Minetest make the tooltip text arbitrarily disappear. But I think I have a plan …

I will rebase once the final bug was fixed (don't want to rebase an unfinished PR over and over).

Also, I should probably improve the DevTest formspec again. There is no test for the tooltip styling yet.

I haven’t chosen a different name for the "supertip" formspec element yet, but I am willing to accept suggestions if there is an consensus. Please comment. (So far only 2 people commented, and I am tending towards @rubenwardy's `tooltip_hypertext`.)

2024-08-18 15:41 UTC, Wuzzy2 commented
New changes:
* Fixed tooltip text disappearing with small window sizes
* Redefined supertip width from formspec units to 'em' units, relative to the default font at unmodified size (i.e. no `<big>` tag, etc.)
* Removed `noclip` from supertip style documentation. I've discussed with kilbith and we decided it was pointless
* Rebase completed

There are no more known bugs left and the supertips work as intended!

Test the new witdth system by using different font sizes in the Minetest config. It should scale. Note the only thing I redefined is the size of a `width` unit, not the underlying logic.

The reason why I picked 'em' units is because it seems the most obvious. As a reminder, 'em' is equal to font size so it neatly scales with the font. Another upside is that the tooltip no longer cares about the window size. This was what caused the old bug: The tooltip size was dependent on formspec units, which in turn is dependent on window size. This didn't make sense to me, so I changed it.

The width system has one inherent downside: The width is not flexible nor automatic. The modder MUST pick a width that kinda leaves enough room. Very generous widths will leave a lot of empty space that isn't truncated. A too small width will cut off text, but it is now the job of the modder to figure this one out. This will also become an issue for translated strings, which vary in length. This isn't a bug, but it may be tricky to find a good width.

So for now, I’d say the recommended use of supertips is generally be more generous with width, just in case.

ANYWAY. The system works as intented tho and is ready for review. And thinking about this, I think we're pretty much *forced* to have to specify a width like that anyway. Because hypertext includes right-justified text and it can't know where the "right-most side" is on its own. It would be great if width could be fully automatically calculated, but I think this is stuff for a new PR (if it is even possible or realistic).

In short, in my opinion this PR is now OFFICIALLY ready for review. All the known bugs are fixed.

2024-08-18 15:46 UTC, Wuzzy2 commented
Oh, one hint for practical usage: If you want a supertip with only one word or line, I recommend to provide more width than the English word (about 1.5×, for the translations) *plus* use `<center>` so the empty space is equally distributed and it looks nicer.

2024-08-20 21:11 UTC, Wuzzy2 commented
Reminder: I rebased, so the label can be removed (for now).

2024-09-22 05:25 UTC, jingkaimori commented on src/gui/guiHyperText.h
> +	void drawBackgroundImage(video::IVideoDriver *driver, const ParsedText &m_text, const core::rect<s32> &clip_rect);
Why passes `ParserdText` as argument in this method? `m_text` can be obtained from instance.

2024-09-28 11:23 UTC, Wuzzy2 commented
Rebased again.

> Why passes ParserdText as argument in this method? m_text can be obtained from instance.

You're right, this argument is not neccessary, so I removed it. It still works.

2024-11-12 12:00 UTC, Wuzzy2 commented
Bump.

2024-12-23 15:13 UTC, Wuzzy2 commented
I just made a fresh new rebase to account for the changes of the last month so it is ready for testing again.

Please someone review this sometime. Everything that has been requested from us has been done and all known bugs are fixed. This PR has already missed several Luanti releases, I wish this nice feature can make it into the next one.

2025-12-12 14:34 UTC, Wuzzy2 commented
I’ve rebased this PR once again, it is once again awaiting review.

I also finally decided to rename the formspec element from `supertip` to `hypertip`. `hypertip` is short for "hypertext tooltip" and faster to type than stuff like `tooltip_hypertext`, `hypertext_tooltip`, etc.

EDIT: Added a "How to test" section in 1st post.

2025-12-13 10:54 UTC, SmallJoker commented on doc/lua_api.md
> +* `staticPos`, `width`, `name`, `text`: See above.
A formspec version bump might make sense such that mods can use whatever first best, or log a warning to the client.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	if (tooltip_x + tooltip_width > (s32)screenSize.X)
Might it be possible to re-use the positioning code from `GUIFormSpecMenu::showTooltip` ? They are very alike.
--> Create a helper function to handle both.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +							m_hypertips.emplace_back(e, spec);
1. Why do the hypertips need caching? Are they slow (take e.g. > 10 ms) to generate?
2. I think it makes more sense to cache this in `showHyperTip`, where the instance is needed the first time.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.h
> +	std::map<std::string, HyperTipSpec> m_hypertip_map;
I would suggest to follow the principle above of `std::vector<std::pair<FieldSpec, GUIHyperText *>>`. That should help to eliminate code that currently treats element-bound tooltips and rect-bound tooltips differently.
It also unifies these two marked members.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
`driver->draw2DRectangle` can be used instead, which is more efficient.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiHyperText.h
> +	void modifyText(const StyleSpec &style);
"modify" means a lot. It's not clear from the function name what this function does, and why. Please add a comment describing its purpose. Perhaps there's a better name too, such as `applyStyleSpec`.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiHyperText.h
> +#include "StyleSpec.h"
Not needed. A forwards decl in the form of `struct StyleSpec;` reduces the header dependencies.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiHyperText.cpp
> +#include "client/guiscalingfilter.h"
Please try to keep it sorted alphabetically. That makes it easier to find certain headers by eye.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.h
> +#include "guiHyperText.h"
Not needed. Please use the forwards decl `class GUIHyperText;` to reduce header dependencies.

2025-12-13 10:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.h
> +		bool bound = false;
Some comments would be helpful.
```suggestion
		v2s32 stpos; //< static tooltip position
		s32 width; //< in pixels
		bool floating; //< whether the position is NON-static (i.e. ignore stpos)
		bool bound = false; //< whether it's cached
```

Or combine `stpos` and `floating`, which seem to belong together anyway:
```suggestion
		std::optional<v2s32> stpos; //< static tooltip position
		s32 width; //< in pixels
		bool bound = false; //< whether it's cached
```

2025-12-13 10:57 UTC, SmallJoker commented
At this point, it might be simplest to squash a few closely related commits (e.g. tests or C++ changes) or yours such that rebasing becomes easier in the future.

2025-12-13 13:49 UTC, kilbith commented
I don't mind my commits being squashed at this point. As long as authorship is respected, of course.

2025-12-13 14:00 UTC, kilbith commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
You probably meant [draw2DRectangleOutline](https://irrlicht.sourceforge.io/docu/classirr_1_1video_1_1_i_video_driver.html#a65efe36e19f0570988848175a8af7bd1) which was removed from IrrlichtMT.

And `draw2DRectangleOutline` was drawing 4x `2DLine` internally.

2025-12-13 14:54 UTC, SmallJoker commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
Oh I see. You're right. Well then - `draw2DVertexPrimitiveList` does exist for batch rendering of any type.

2025-12-13 21:40 UTC, Wuzzy2 commented on doc/lua_api.md
> +* `staticPos`, `width`, `name`, `text`: See above.
I'm not sure if I understand this. Why is a formspec version bump needed? It doesn't seem the version was bumped each time a new element was added, right?

2025-12-13 21:58 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +							m_hypertips.emplace_back(e, spec);
I probably should test the performance, if it's fast, maybe I'll drop caching entirely.

2025-12-14 13:57 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
IMO `draw2DVertexPrimitiveList` seems a bit excessive optimization for only 4 lines that appear on the screen once for 1 tooltip. Also makes the code more bloated. \*shrug\*

(or did I misunderstand the goal here?)

2025-12-14 14:45 UTC, SmallJoker commented on doc/lua_api.md
> +* `staticPos`, `width`, `name`, `text`: See above.
It's not "*needed*" but "*might make sense*". If you think that the protocol version number bump for on each release is sufficient, then that's fine by me.

2025-12-14 14:47 UTC, SmallJoker commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
I did not express myself very well. This is an idea, not a change request. ("*can be used*" vs "*please use*" (or similar)).

2025-12-14 18:10 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +							m_hypertips.emplace_back(e, spec);
OK, in my tests it can sometimes take 25ms to create a more complex tooltip, so I guess I leave this code as-is. (I really don't want to make a lot of code changes anymore unless neccessary tbh.)

2025-12-14 18:12 UTC, Wuzzy2 commented on doc/lua_api.md
> +* `staticPos`, `width`, `name`, `text`: See above.
So if I decide to not bump the formspec version, that's OK?
In my tests, old clients will simply ignore any hypertip element with no error.

2025-12-14 18:13 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +		driver->draw2DLine(UpperLeft, core::position2di(LowerRight.X, UpperLeft.Y), color);
OK, I leave this code alone then.

2025-12-14 18:47 UTC, Wuzzy2 commented on src/gui/guiHyperText.h
> +#include "StyleSpec.h"
This file needs to know `StyleSpec::NUM_STATES` tho.

2025-12-14 19:06 UTC, Wuzzy2 commented
So most comments are addressed now. I will not do a squash for now until the PR is deemed acceptable. I hope to address the final open comment soon(ish).

(My philosophy is, first get this thing in an acceptable state, THEN do whatever commit cleanup is neccessary. Not the other way around.)

2025-12-15 09:21 UTC, nerzhul commented
thanks @Wuzzy2 for your efforts on this one

2025-12-22 15:54 UTC, SmallJoker reviewed
Works OK... with caveats highlighted in the comments.

2025-12-22 15:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	}
1. `precheckElement` is supposed to ease backwards compatibility. With such additional checks, it will not be possible to extend this formspec element (i.e. more params) in the future. 
2. This check (L1774) is flawed. Currently it compares `a == b && a == b + 2` which is always `false`.

```suggestion
	const bool rect_mode = parts[0].find(',') != std::string::npos;
	const size_t base_size = rect_mode ? 6 : 5;
	if (parts.size() < base_size) {
		errorstream << "Invalid hypertip element(" << parts.size() << "): '"
				<< element << "'"  << std::endl;
		return;
	}
```

2025-12-22 15:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +		}
According to the documentation of this PR, `staticPos` is always in the format `x,y`. Hence:

```suggestion
		if (v_stpos.size() != 2) {
			errorstream << "Invalid staticPos in hypertip element(" << parts.size() <<
				"): \"" << parts[i] << "\"" << std::endl;
			return;
		}
```
(this is very similar to `MY_CHECKPOS`)

2025-12-22 15:54 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	s32 tooltip_height = e->getTextHeight() + 5;
This does not seem to be correct in all cases:
<img width="390" height="169" alt="grafik" src="https://github.com/user-attachments/assets/7b612ee3-29ad-40fc-b0df-3db9d3db3212" />

The full tooltip is drawn like this:
<img width="182" height="163" alt="grafik" src="https://github.com/user-attachments/assets/5f60a24d-a4ce-42f9-97f6-66bb51eb9692" />

By making the contents of `hypertip[1,11;1,1;;8;` longer, I do notice that the tooltip size is restricted, even though there would be enough space towards the top (Y-).
Unrelated finding: It takes three iterations for `e->getTextHeight()` to return a constant height value. Is this some side-effect of automatic content sizing? In extreme cases, the first value is `1076366678`, followed by `6` and then a constant `97`.

This is the fix that I've come up with eventually:
```C++
	// Calculate and set the tooltip position
	if (spec.floating) {
		/* Dynamic tooltip position, relative to cursor */
		positionTooltip(tooltip_width, tooltip_height, tooltip_x, tooltip_y);
	} else {
		/* Static tooltip position, using formspec coordinates */
		tooltip_x = spec.stpos[0];
		tooltip_y = spec.stpos[1];
	}

	if (tooltip_x + tooltip_width  + m_btn_height > (s32)screenSize.X)
		tooltip_x = (s32)screenSize.X - tooltip_width  - m_btn_height;
	if (tooltip_y + tooltip_height + m_btn_height > (s32)screenSize.Y)
		tooltip_y = (s32)screenSize.Y - tooltip_height - m_btn_height;

	if (spec.floating) {
		v2s32 base_pos = e->getParent()->getAbsolutePosition().UpperLeftCorner;
		tooltip_x -= base_pos.X;
		tooltip_y -= base_pos.Y;
	}
```

2025-12-22 17:09 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	}
1. How so? Can't we just update all the checks in this function whenever a new argument is added? And increase the upper bound of `precheckElement` by 1? Would require a bit extra code for checks but I don't see how this makes it literally impossible to solve. An alternative solution would be to change the syntax of `hypertext` to circumvent this (but I don't know which syntax would be better).
2. Fixed. Also renamed the confusingly named `i` to `staticPosIndex`.

2025-12-22 17:16 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	}
FYI
> Use snake_case for local variables, not camelCase

https://docs.luanti.org/for-engine-devs/code-style-guidelines/#miscellaneous

(Though, in this case I won't insist)

2025-12-22 17:39 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	s32 tooltip_height = e->getTextHeight() + 5;
I've applied your fix but I removed the `m_btn_height` offset so that the hypertip now ends directly at screen boundaries. Using `m_btn_height` seems like a strange choice for a tooltip offset anyway.
With this fix, the tooltip now neatly ends at the right/bottom boundaries.

The `getTextHeight()` finding is strange. No idea what causes this but I try to look if I find something weird. Did this happen in other places of the code where `getTextHeight()` is called, too?

2025-12-22 19:30 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	s32 tooltip_height = e->getTextHeight() + 5;
> but I try to look if I find something weird

I have not spent the time to investigate this further, but sometimes I can see the "hypertip" to quickly flicker, which seems to correspond to the values I got from there. Not sure if it's related to this PR. Feel free to insert some logging lines to narrow things down, but I don't see much priority there.

> so that the hypertip now ends directly at screen boundaries.

It does help in cases where you are not sure whether the entire tooltip is shown or cut off - especially when there's no border or such that cannot be seen easily. I also found that gap helpful while writing this code proposal to ensure proper clipping.
I agree that `m_btn_height` is a strange choice and that it should be replaced with a separate constant value for both - tooltips and hypertips - to stay consistent.

2025-12-23 11:16 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	}
> Can't we just update all the checks in this function whenever a new argument is added?

Unfortunately it is not possible to change code of prior engine builds. Older clients would simply reject the formspec element, regardless on whether or not the new parameter(s) are backwards compatible.

2025-12-23 13:37 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	}
OK, so how to do it right then? Is there like a list of criteria to make a formspec element forwards-compatible? That would help.
One idea would be that in the case of element-bound hypertips, the 2nd argument is simply ignored, so that in both cases (element bound, or formspec rectancle) the number of arguments is the same. Would that be enough to fix this problem?

2025-12-23 13:49 UTC, Wuzzy2 commented
Regarding the `e->getTextHeight()` returning inconsistent values at start: After some debugging, I think I narrowed down this problem a bit.

The inconsistent height comes from `TextDrawer::place` in `src/gui/guiHyperText.cpp`, it writes to `m_height` at the end and in my debugging this is where the value can end up inconsistent initially. Somewhere in this function something weird happens.

I also noticed that `m_height` is not initialized which explains the first weird value, but this is not the full explanation. Initializing it does not fix the problem entirely, the value stilll "bounces around" for a few steps before stabilizing, probably caused by `TextDrawer::place`.

It will take more time to figure out the exact reason.

Edit: Fixed the flicker by waiting 1 tick more in the draw function. Callers should now wait for `m_draw_state` to be 2 before they can trust `getHeight`.

2025-12-23 14:32 UTC, SmallJoker commented on src/gui/guiFormSpecMenu.cpp
> +	}
`precheckElement` already does the most important part: it ensures there's 5 to 6 arguments but allows more if the formspec version is higher than what the client knew at compile time (i.e. when the element is newer).
Afterwards it is only necessary to ensure that there's enough arguments for position-bound hypertips. This is what my proposed change above (L1781 and L1782) does.

Future additions or changes to this element (i.e. not in this PR) will require a formspec version bump to make it work on older clients.

2025-12-23 14:47 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	}
I already applied the suggested change. If that's enough to satisfy the compatibility requirements, I think this one can be marked as resolved then. Oh, and I just applied the snake case.

2025-12-23 14:53 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	s32 tooltip_height = e->getTextHeight() + 5;
I personally prefer to use no offset at all and it looks OK in my tests. And IMO with offset it looks a little weird, especially on larger resolution.
But if an offset is desired, I can add a small fixed pixel offset.

For testing, you could make a test formspec where a hypertip activates on a very large rectangle area to ease testing near the boundaries.

2025-12-23 20:27 UTC, SmallJoker approved these changes
Works well enough.

2026-01-04 00:01 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	s32 tooltip_height = e->getTextHeight() + 5;
I banged my head against this code for a LONG time and finally figured out what was happening. The element position initially start at (0,0) and is only updated in later calls to the `place` function. Adding a floating element in the hypertext will influence the positioning. Multiple iterations are needed before the values stabilize.

To fix the "flicker", I simply made the draw function wait one more tick before it actually draws.

2026-01-04 00:06 UTC, Wuzzy2 commented
@nerzhul: GitHub claims you are still "requesting changes" but I think everything is already addressed?

Anyway, just fixed a small "flicker" bug and I guess this PR is fully ready again.

2026-01-30 00:18 UTC, Wuzzy2 commented
This PR is ready for review again (freshly rebased).

2026-02-12 20:01 UTC, appgurueu commented on games/devtest/mods/testformspec/formspec.lua
> +			hypertip[1,7;1,1;;18;hypertip_dynamic_complex;]]..minetest.formspec_escape([[<big>Complex hypertip (<i>dynamic</i>)</big>
```suggestion
			hypertip[1,7;1,1;;18;hypertip_dynamic_complex;]]..core.formspec_escape([[<big>Complex hypertip (<i>dynamic</i>)</big>
```

nit. same below.

2026-02-12 20:01 UTC, appgurueu commented on games/devtest/mods/testformspec/formspec.lua
> +<center>Right align</center>
```suggestion
<center>Center align</center>
```

2026-02-12 20:01 UTC, appgurueu commented on src/gui/guiHyperText.cpp
> +	if (m_draw_state >= 2) {
This feels like one hell of a hack, with potential negative implications (like noticeable jank: i assume this translates to 2 frames of delay?)

Is there no decently simple way to figure out what this depends on, and make sure the drawing proceeds in such an order that dependencies are fulfilled? e.g., do the drawing in stages, where hypertips are drawn last?

2026-02-12 20:01 UTC, appgurueu commented on src/gui/guiHyperText.cpp
> +		m_text.background_color = style.getColor(StyleSpec::BGCOLOR, video::SColor(255,110,130,60));
where does this random color come from?

2026-02-12 20:01 UTC, appgurueu commented on src/gui/guiFormSpecMenu.cpp
> +	const size_t base_size = rect_mode ? 6 : 5;
style: this `rect_mode ? (x + 1) : x` pattern seems brittle and unreadable to me.

i would prefer having one variable, say `size_t cursor = 1;`, that is advanced `if (rect_mode)`, and every time something is extracted.

so you get something like `std::string name = parts[cursor++];` which just works

2026-02-12 20:29 UTC, kilbith commented on src/gui/guiHyperText.cpp
> +	if (m_draw_state >= 2) {
IIRC (it's been a long time since I've touched this code), it's depending on `TextDrawer::place` not being ready to determine the correct text dimensions to draw the tooltip with. Note the delay is the 2 first frames *ever* after the tooltip is requested to draw. It's not even remotely noticeable by the user.

2026-02-13 12:55 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +		m_text.background_color = style.getColor(StyleSpec::BGCOLOR, video::SColor(255,110,130,60));
This is just the default tooltip green: `rgb(110,130,60)`

2026-02-13 13:36 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	const size_t base_size = rect_mode ? 6 : 5;
Done.

2026-02-13 13:43 UTC, Wuzzy2 commented
@appgurueu: Comments addressed.

2026-02-13 14:21 UTC, kilbith commented on src/gui/guiFormSpecMenu.cpp
> +	arg_cursor++;
All of this is superfluous: 

```C++
foo = bar[idx];
idx++;
```

You can just: `foo = bar[idx++];` since incrementation happens after assignment.

2026-02-13 15:19 UTC, appgurueu commented on src/gui/guiFormSpecMenu.cpp
> +	arg_cursor++;
(technically: whether the increment happens before or after assignment is not important, what's important is that `idx++` evaluates to to the old value of `idx` so this is guaranteed to work as expected)

2026-02-13 17:53 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	arg_cursor++;
Oops, I just forgot to do it; I picked the longer form first for readability of my diff.

2026-02-13 18:16 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.cpp
> +	arg_cursor++;
Fixed.

2026-02-13 18:17 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +	if (m_draw_state >= 2) {
I can confirm the delay is practically 0 from the user’s point-of-view.

2026-02-13 22:48 UTC, CrazyladMT commented on src/gui/guiHyperText.cpp
> +		m_text.background_color = style.getColor(StyleSpec::BGCOLOR, video::SColor(255,110,130,60));
Wait this already exists as `m_default_tooltip_bgcolor`

https://github.com/luanti-org/luanti/blob/137fbc65a07047a4a1680001b784781bd2cc0136/src/gui/guiFormSpecMenu.h#L377

https://github.com/luanti-org/luanti/blob/137fbc65a07047a4a1680001b784781bd2cc0136/src/gui/guiFormSpecMenu.cpp#L3062

2026-02-16 08:26 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +		m_text.background_color = style.getColor(StyleSpec::BGCOLOR, video::SColor(255,110,130,60));
Yes, this hardcoding was bad. I fixed it. Tooltips now take the "global" tooltip color by default, including the one set by `listcolors[]`.

2026-02-16 08:29 UTC, Wuzzy2 commented
It turned out that hypertip had a hardcoded text and background default color, ignoring the global defaults as well as `listcolors[]`.
I rewrote the code so that hypertips will now use the global default tooltip colors instead, unless an explict style or hypertext color overwrites it. `listcolors[]` now affects the default colors for hypertips as well.

I've updated the DevTest formspec tests accordingly.

2026-02-16 08:46 UTC, Wuzzy2 commented on src/gui/guiHyperText.cpp
> +	if (m_draw_state >= 2) {
Since kilbith already explained it well and there are no further replies so far, I’m going to resolve this for now. If you disagree, just re-open.

2026-05-11 08:25 UTC, The4codeblocks commented
this
is
very nice

2026-05-16 08:41 UTC, Wuzzy2 commented
I rebased this PR again and tested if it still works, and it still works for me.

2026-06-30 16:59 UTC, appgurueu reviewed
Mostly looking good! Sorry for the late review.

One more minor thing: Shouldn't the margin be on all sides? It looks like the top margin is added to the bottom. This creates an awkward empty space at the bottom.

<img width="163" height="133" alt="Image" src="https://github.com/user-attachments/assets/0ac68a51-e83b-49c8-a879-24d42d6b6f48" />

2026-06-30 16:59 UTC, appgurueu commented on src/gui/guiFormSpecMenu.h
> +		HyperTipSpec() = default;
I think both these constructors can be dropped. For the second constructor, just use aggregate initialization (`HyperTipSpec{...}` instead of `HyperTipSpec(...)`, might want to default-initialize the primitive fields so they can't go uninitialized). This is more fitting for such a data struct.

2026-06-30 16:59 UTC, appgurueu commented on src/gui/guiFormSpecMenu.h
> +		v2s32 stpos; //< static tooltip position
```suggestion
		v2s32 stpos; ///< static tooltip position
```

pretty sure triple `/` is needed for doxygen to pick up on it (https://www.doxygen.nl/manual/docblocks.html)

same below

2026-06-30 18:31 UTC, kilbith commented
> One more minor thing: Shouldn't the margin be on all sides? It looks like the top margin is added to the bottom. This creates an awkward empty space at the bottom.

[Hardcoded margin](https://github.com/luanti-org/luanti/pull/14728/changes#diff-d518daac1f5499b49517a02957e29771288333e58227308b7711cc5da6bd1544R4023) on the bottom for consistency with [tooltips](https://github.com/luanti-org/luanti/blob/master/src/gui/guiFormSpecMenu.cpp#L3685).

IMO it should go as hypertext can already do margin on its own.

2026-06-30 20:50 UTC, Wuzzy2 commented
> Shouldn't the margin be on all sides?

Yeah. This was inherited from the hypertext behavior. It seems this was a bug in that the margin does not apply correctly to the top. This was because paragraph and element margins took precedence even for the first paragraph. (Paragraphs and elements have their own hardcoded margins). I have made a commit which fix this, which affects both hypertext and hypertip elements.

Please test.

> IMO it should go as hypertext can already do margin on its own.

Done.

2026-06-30 20:54 UTC, Wuzzy2 commented on src/gui/guiFormSpecMenu.h
> +		HyperTipSpec() = default;
I’m not too happy with such a change, all the other structs in that file use explicit notation, so this suggestion would break the consistency in the file. Also, the official coding style appears to be silent on constructors, so …

I think it’s better to do *general* code-style changes outside of this PR.

2026-06-30 22:29 UTC, appgurueu commented on src/gui/guiFormSpecMenu.h
> +		HyperTipSpec() = default;
The reason I suggested it is that seeing the changes in this PR (and how I expect the struct to be used in the future), I know that my suggestion results in neater code overall. [^init]

But fair enough, I hadn't examined the surrounding style. It's fine to leave that consistent for now.

I will propose some changes to our style guide eventually, it is silent on too many things.

[^init]: There is a detail with regard to initialization of primitives that don't get default-initialized (e.g. `bool`), a constructor can force their initialization. But the proper solution is simply to give each member a default initializer (e.g. `= false` for `bool`). You have to do this anyways if you want a default constructor that doesn't leave members uninitialized. (The current default constructor does.) Well whatever, off to the style guide rationale it goes...

2026-06-30 22:30 UTC, appgurueu approved these changes
Looks correct to me. The `hypertext[]` in `/test_formspec` still renders basically the same as on 5.11 and 5.17-dev, which is with the margin applied on all sides as expected:
<img width="782" height="254" alt="image" src="https://github.com/user-attachments/assets/e4be3dd7-1685-4e1c-af79-ac379ff688fa" />

The tooltips also look fine now, the margins are symmetric on all sides as they should be :+1:

2026-07-01 22:42 UTC, merged

2026-07-01 23:02 UTC, The4codeblocks commented
yay

2026-07-02 17:50 UTC, CrazyladMT commented
Glad to see this feature get merged! It's a nice addition, and it will be cool experimenting with it :)

That said, it's hard to ignore the fact that **every single** comment of @kilbith's was hidden as abuse (including some technically useful ones!!), right after his last PR got merged nonetheless. Just feels excessive and counterproductive.

To quote @Zughy from https://github.com/luanti-org/luanti/pull/17086#issuecomment-4188923741...

> free software is about human connections, learning from others, community, onboarding.

This is the opposite.