Add --terminal-silent flag to minetest
minetest/minetest pull request #14734
Opened 2024-06-07 10:42 UTC by jordan4ibanez

Add compact, short information about your PR for easier understanding:

It allows you to hook in GUIs and also as a side effect you can type straight into the regular terminal.

- Goal of the PR
Some way to directly talk to minetest through the command line.
- How does the PR work?
It uses cin nonblocking with sleep on another thread via the ILogOutput and Thread parent classes to get this pipe dream functioning.
- Does it resolve any reported issue?
I have no idea.
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
Still no idea.
- If not a bug fix, why is this PR needed? What usecases does it solve?
Because you should be able to talk to your local server through the terminal when it's being handled by other apps.

## To do
- Think of a better pr name.

This PR is a Ready for Review.

- [x] Cry because ncurses is so painful to work with.
- [x] Give up and try 50 other approaches.
- [x] Find a solution.

## How to test

Build with this thing, launch ``minetestserver`` or ``minetest --server`` with the flag ``--terminal-silent`` and then type straight into the terminal

2024-06-07 18:33 UTC, SwissalpS commented
> then type straight into the terminal.

any examples of what to type?

2024-06-08 01:53 UTC, jordan4ibanez commented
> > then type straight into the terminal.
> 
> any examples of what to type?

``hi``
``/shutdown``
``an example of what to type``

2024-06-08 02:09 UTC, jordan4ibanez commented
In case there's any other confusion as to what I mean by, you can directly type into the terminal (stdin), here is an image.
![image](https://github.com/minetest/minetest/assets/1088750/67ee065f-42a4-4150-994c-4abf7221ecaa)

2024-06-08 13:16 UTC, jordan4ibanez commented
Here is a video of a use case for it: https://youtu.be/X2O0gKai1CI

Here is the repo for the gui used in the video: https://github.com/jordan4ibanez/minetest_gui

2024-07-02 21:01 UTC, sfan5 requested changes

2024-07-02 21:01 UTC, sfan5 commented on src/terminal_chat_console_silent.cpp
> +			std::this_thread::sleep_for(std::chrono::milliseconds(10));
no need for nonblock (which afaik could also cause problems with logging) and the sleeping.
you can simply `poll` with a timeout of e.g. 1s (so it still exits correctly)

2024-07-02 21:01 UTC, sfan5 commented on src/terminal_chat_console_silent.cpp
> +		m_chat_backend.addMessage(L"", (std::wstring)L"Issued command: " + msg);
`m_chat_backend` is totally unused except for this

2024-08-12 10:19 UTC, closed without merging