Warn contributors about not to run updatepo.sh manually
minetest/minetest pull request #14845
Opened 2024-07-12 00:44 UTC by Emojigit

This PR adds one line in `.github/CONTRIBUTING.md` warning contributors not to run `updatepo.sh`.

I was confused while contributing in #14842 on whether I should be responsible for updating the translation files. Though running the script was a disaster, I found nothing that warned me not to update.

## To do

This PR is Ready for Review.

## How to test

Navigate to the file on GitHub.

2024-07-12 08:14 UTC, rollerozxa commented
Could mention minetest.conf.example and settings_translation_file too that they are automatically generated, you don't need to manually edit them in your own PR when changing stuff in settingtypes.txt and they will get automatically updated during feature freeze right before release.

2024-07-13 10:34 UTC, Emojigit commented
@rollerozxa Done in 30e40622e

2024-07-17 22:36 UTC, JosiahWI requested changes
Looks good, one word smithing request.

2024-07-17 22:36 UTC, JosiahWI commented on .github/CONTRIBUTING.md
> +      - Update `minetest.conf.example` and `settings_translation_file.cpp` even if you code adds new core settings.
```suggestion
      - Update `minetest.conf.example` and `settings_translation_file.cpp` even if your code adds new core settings.
```

2024-07-17 23:18 UTC, JosiahWI approved these changes
Thanks for adding this advice, I like more documentation.

2024-07-18 08:45 UTC, sfan5 approved these changes

2024-07-20 08:24 UTC, merged