Refactor tool.cpp
minetest/minetest pull request #14873
Opened 2024-07-20 19:08 UTC by wrrrzr

Refactor tool.cpp using Guard Expressions and Extract Method

2024-07-21 11:30 UTC, JosiahWI requested changes
Thanks for applying these refactorings. They're pretty straightforward and this should have no behavioral change, but I'd like to clean up the extracted methods a little more.

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +void ToolCapabilities::deserializeJsonGroupcaps(Json::Value &object) {
This parameter is named `json` in other places, so let's keep it consistent. I think `json` is more descriptive anyway.

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +	ToolGroupCap value;
Could we declare these closer to their first uses?

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +		value.fromJson(*iter);
The name `value` doesn't seem very descriptive here. Maybe something like `groupCap`?

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +void ToolCapabilities::deserializeJsonDamageGroups(Json::Value &object) {
Could we rename the parameter to `json`?

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +		Json::Value &value = *iter;
Why is the pattern different from `deserializeJsonGroupcaps`?

2024-07-21 11:30 UTC, JosiahWI commented on src/tool.cpp
> +		Json::Value &value = *iter;
Again, not a very descriptive name.

2024-07-21 11:56 UTC, wrrrzr commented
> Thanks for applying these refactorings. They're pretty straightforward and this should have no behavioral change, but I'd like to clean up the extracted methods a little more.

ok, I cleaned up the extracted methods. But I think it's better to call the variable in the loop "value" because it has a small scope.

2024-07-21 12:14 UTC, JosiahWI commented on src/tool.cpp
> +		Json::Value &value = *iter;
It looks like `ToolGroupCap` is an object and `fromJson` is a method we defined on it, whereas this is just an integer.

2024-07-21 12:28 UTC, JosiahWI approved these changes
Looks good. Tested in MTG with bronze ax, cobble pick, and diamond pick: dig times for different nodes and tool uses still work.

2024-08-18 16:40 UTC, sfan5 commented on src/tool.cpp
> +void ToolCapabilities::deserializeJsonGroupcaps(Json::Value &json) {
```suggestion
void ToolCapabilities::deserializeJsonGroupcaps(Json::Value &json)
{
```

2024-08-18 16:40 UTC, sfan5 commented on src/tool.cpp
> +void ToolCapabilities::deserializeJsonDamageGroups(Json::Value &json) {
```suggestion
void ToolCapabilities::deserializeJsonDamageGroups(Json::Value &json)
{
```

2024-08-18 16:40 UTC, sfan5 commented on src/tool.h
> +private:
```suggestion

private:
```

2024-08-19 08:14 UTC, wrrrzr commented on src/tool.h
> +private:
> 

ok, i apply suggestions

2024-08-19 13:10 UTC, sfan5 approved these changes

2024-08-19 18:09 UTC, appgurueu approved these changes
Code is ok. I agree that the two variables named "value" could be named better but that isn't necessary IMO.

2024-08-21 18:24 UTC, merged