docs(locale): pt_BR localization to builtin
minetest/minetest pull request #14902
Opened 2024-07-29 01:00 UTC by YunaSatoy

Addition of Brazilian Portuguese localization to builtin `__builtin.pt_BR.tr`.

2024-08-05 14:00 UTC, srifqi requested changes
There are some issues.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +[all | privs | <cmd>] [-t]=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> + (@1 s)=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +<action>=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +<name> (<privilege> [, <privilege2> [<...>]] | all)=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +<privilege> [, <privilege2> [<...>]] | all=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +<X>,<Y>,<Z> | <to_name> | <name> <X>,<Y>,<Z> | <name> <to_name>=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +(here [<radius>]) | (<pos1> <pos2>)=
This has not been translated. Even if it is the same, please also write it.

2024-08-05 14:00 UTC, srifqi commented on builtin/locale/__builtin.pt_BR.tr
> +print [<filter>] | dump [<filter>] | save [<format> [<filter>]] | reset=
This has not been translated. Even if it is the same, please also write it.

2024-08-09 12:44 UTC, YunaSatoy commented
> There are some issues.

Thanks for the review. I made the necessary corrections! :blush:

2024-08-09 15:00 UTC, srifqi reviewed
The translation is complete and no syntax error is found. (Oops, I chose the wrong type of review.)

2024-08-10 00:00 UTC, srifqi approved these changes
The translation is complete and no syntax error is found.

2024-08-11 12:38 UTC, merged