Hardening made easy
minetest/minetest pull request #14941
Opened 2024-08-09 16:03 UTC by okias

Debian and Mobian would be very grateful, if build-system would be able to accept distribution options (in case of Debian mostly focus on hardening) by default without need of patching.

Follow up of:
 - https://github.com/minetest/minetest/pull/12799
 - https://github.com/minetest/irrlicht/pull/134

2024-08-09 16:14 UTC, sfan5 commented on src/CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_CFLAGS} $ENV{CFLAGS} $ENV{CPPFLAGS}")
is `CMAKE_CFLAGS` a typo?

2024-08-09 16:37 UTC, okias commented on src/CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_CFLAGS} $ENV{CFLAGS} $ENV{CPPFLAGS}")
definitely, fixed now

2024-08-11 17:58 UTC, sfan5 commented on src/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG ${RELEASE_WARNING_FLAGS} ${OTHER_FLAGS} -pipe -funroll-loops -O3 -fomit-frame-pointer $ENV{CPPFLAGS}")
```suggestion
	set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG ${RELEASE_WARNING_FLAGS} ${OTHER_FLAGS} -pipe -funroll-loops -O3 -fomit-frame-pointer $ENV{CPPFLAGS}")
```

2024-08-12 10:51 UTC, okias commented
Btw. while it has characteristic of feature from game perspective, I would say it's more like bug-fix for distro packaging :)

2024-08-17 14:02 UTC, sfence requested changes
PR works as expected.
It should be documented somewhere somehow.
Probably `doc/compiling/README.md `?

2024-10-02 17:51 UTC, closed without merging

2024-10-03 04:42 UTC, okias commented
Thank you for ping, feel free to reopen when suitable.

2024-10-03 05:09 UTC, sfence commented
@okias Feel free to reopen PR when you've updated the documentation.

2024-10-03 09:52 UTC, okias commented
I updated doc before the comment, I CANNOT reopen.

2024-10-03 09:54 UTC, grorp commented
Since you force-pushed, nobody can reopen this PR AFAICT 🙃

2024-10-03 10:02 UTC, okias commented
you could just ping me instead closing. Anyway follow-up here: https://github.com/minetest/minetest/pull/15230