Fix chance/probability wording in lua_doc.md
minetest/minetest pull request #14974
Opened 2024-08-15 09:49 UTC by kno10

Documentation improvement. The probability is 1/chance, not "the chance is 1/chance".

Also, unfortunately, only integers are currently possible (why not float?)

2024-08-15 10:13 UTC, sfan5 approved these changes

2024-08-16 03:00 UTC, srifqi requested changes

2024-08-16 03:00 UTC, srifqi commented on doc/lua_api.md
> +    -- Probabilitiy of triggering `action` per-node per-interval is 1.0 / chance (integers only)
```suggestion
    -- Probability of triggering `action` per-node per-interval is 1.0 / chance (integers only)
```

2024-08-16 03:00 UTC, srifqi commented
> Also, unfortunately, only integers are currently possible (why not float?)

The calculation uses the remainder operator (`%`) which only works for integers.

https://github.com/minetest/minetest/blob/dc7a7a0ed98e10f80c7ca5ce071300ada7922eab/src/serverenvironment.cpp#L966-L967

(Literally, 1 in `chance`.)

2024-08-16 19:59 UTC, merged

2024-08-17 20:42 UTC, kno10 commented
> > Also, unfortunately, only integers are currently possible (why not float?)
> 
> The calculation uses the remainder operator (`%`) which only works for integers.
> 
> https://github.com/minetest/minetest/blob/dc7a7a0ed98e10f80c7ca5ce071300ada7922eab/src/serverenvironment.cpp#L966-L967
> 
> (Literally, 1 in `chance`.)

@srifqi use `myrand_float() * chance < 1`?