Serverlist: Add ping indicators
minetest/minetest pull request #5164
Opened 2017-02-02 17:23 UTC by kilbith

![2017-02-02-175147_1366x768_scrot](https://cloud.githubusercontent.com/assets/7883281/22560370/9d5f2e3e-e974-11e6-9e74-871f225ebaa8.png)

2017-02-02 18:54 UTC, SmallJoker commented
Very nice. I would prefer having it with two textures: Shadow and overlay. But currently that would take too many texture modifiers to make it look right, so it's fine this way.
:+1:

2017-02-02 19:08 UTC, lisacvuk commented
Maybe also allow user to set it to display ping in ms, rather than an icon?

2017-02-02 19:53 UTC, nerzhul requested changes

2017-02-02 19:53 UTC, nerzhul commented on src/script/lua_api/l_mainmenu.cpp
> +		if (servers[i]["ping"].asString().size()) {
please store the string before condition and use !str.empty() and re-use the stored string into function instead of converting json value twice

2017-02-02 21:29 UTC, sfan5 commented
hm
I think it would look nicer if the ping indicators were left of the player count, can you try that?

2017-02-02 21:31 UTC, sfan5 commented on src/script/lua_api/l_mainmenu.cpp
> +			lua_pushstring(L, str_ping.c_str());
why not convert it to int?

2017-02-02 21:32 UTC, sfan5 commented on builtin/mainmenu/common.lua
> +			details = details .. "5,"
so nothing is displayed if the ping is > 999?

2017-02-02 22:33 UTC, kilbith commented
Addressed @sfan5 comments. Preview updated.

2017-02-02 22:35 UTC, rubenwardy commented on builtin/mainmenu/common.lua
> +		elseif ping <= 500 or ping > 500 then
can just use else here

2017-02-03 06:34 UTC, nerzhul approved these changes

2017-02-03 06:35 UTC, nerzhul commented
okay for me

2017-02-03 10:29 UTC, sfan5 commented on src/script/lua_api/l_mainmenu.cpp
> +		if (ping) {
this `if` seems incorrect to me
what does `asFloat()` return if the element doesn't exist or isn't a float?

2017-02-03 10:32 UTC, nerzhul commented on src/script/lua_api/l_mainmenu.cpp
> +		if (ping) {
the if should be servers[i].hasMember("ping")

2017-02-03 10:41 UTC, kilbith commented on src/script/lua_api/l_mainmenu.cpp
> +		if (ping) {
I wasn't sure about it. According to my readings, the variable will be uninitialized (undefined behavior) since it's a local variable.

2017-02-03 11:37 UTC, Zeno- commented on src/script/lua_api/l_mainmenu.cpp
> +		if (ping) {
asFloat() needs fixing, yes. That function (asFloat()) should not drop off the end of the function without a return IMO

2017-02-03 13:14 UTC, kilbith commented on src/script/lua_api/l_mainmenu.cpp
> +		if (ping) {
So it's `isMember()`, not `hasMember()`. Fixed.

2017-02-03 13:28 UTC, sfan5 approved these changes

2017-02-03 13:53 UTC, Zeno- commented
:+1:

2017-02-03 13:53 UTC, merged

2017-02-03 18:15 UTC, Fixer-007 commented
Nice!