FormSpec: Add position and anchor elements
minetest/minetest pull request #5284
Opened 2017-02-20 12:47 UTC by adelcoding1

**Description :** 
- `position` element can be used after "size" element
- `anchor` element can be used after "position" element or "size" element (if "position" element is not used)

**Usage :**
- `position` element sets the position of the widget on the screen
- `position[0,5, 0.5]` sets position on the center of the screen (the default value if not used)
- `position[0,0, 0.0]` sets the widget to the Top Left of the screen
- `position[1,0, 0.0]` sets the widget to the Top Right of the screen
- `position[0,0, 1.0]` sets the widget to the Bottom Left of the screen
- `position[1,0, 1.0]` sets the widget to the Bottom Right of the screen

- `anchor` element sets the anchor of the Form Spec
- `anchor[0,5, 0.5]` sets the anchor in the center of the Form Spec (the default value if not used)
- `anchor[0,0, 0.0]` sets the anchor in the Top Left of the Form Spec
- `anchor[1,0, 0.0]` sets the anchor in the Top Right of the Form Spec
- `anchor[0,0, 1.0]` sets the anchor in the Bottom Left of the Form Spec
- `anchor[1,0, 1.0]` sets the anchor in the Bottom Right of the Form Spec

**Examples :**
- `size[6,4]position[0.5,0.5}anchor[0.5,0.5}` set the position of the Form Spec on the center of the screen
- `size[6,4]position[1.0,1.0}anchor[1.0,1.0}` set the position of the Form Spec on the Bottom Right of the screen

2017-02-20 13:55 UTC, nerzhul requested changes
Please fix the point mentionned below

2017-02-20 13:55 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +bool GUIFormSpecMenu::parsePositionDirect(parserData * data, std::string element)
std::string should be passed as const ref to prevent useless copy.

2017-02-20 13:55 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +	if (element == "")
element.empty()

2017-02-20 13:55 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +void GUIFormSpecMenu::parsePosition(parserData * data, std::string element)
please look at the code style rules, pointers should not add extra space after asterisk

2017-02-20 13:55 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +	{
brace on wrong line

2017-02-20 15:43 UTC, rubenwardy commented on src/guiFormSpecMenu.cpp
> +	errorstream << "Invalid size element (" << parts.size() << "): '" << element << "'" << std::endl;
copy-pasta mistake

2017-02-20 15:43 UTC, rubenwardy commented on src/guiFormSpecMenu.cpp
> +	errorstream << "Invalid size element (" << parts.size() << "): '" << element << "'" << std::endl;
here too

2017-02-24 13:20 UTC, nerzhul approved these changes
okay for me

2017-02-24 14:01 UTC, Ekdohibs approved these changes

2017-02-25 12:19 UTC, nerzhul commented
can you add formspec documentation ?

2017-02-25 12:19 UTC, nerzhul requested changes
missing formspec doc

2017-03-02 18:47 UTC, nerzhul approved these changes
Okay for me

2017-03-04 09:46 UTC, merged

2017-10-25 07:42 UTC, paramat commented
@adelcoding1 can you explain why 'anchor' is needed as well a 'position' to move a formspec on the screen? Why not 'position' only?

2017-10-25 12:17 UTC, kilbith commented
`anchor` is needed so that it indicates the direction where the formspec extends. If you set the position of your formspec on the bottom-right, and that you misplace your anchor, the formspec will goes offscreen. In that case `anchor` permits to extend the formspec size from the bottom-right to the top-left.

Is it clear enough?

2017-11-01 08:39 UTC, paramat commented
Yes thanks, 'anchor' is the position within the formspec that is anchored to the specified 'position'.

2017-11-01 08:46 UTC, kilbith commented
Yes, exactly.