Formspec: Add support for vertical scrollbar in textarea
minetest/minetest pull request #5299
Opened 2017-02-24 10:54 UTC by adelcoding1

- textarea Formspec uses now a `GUIEditBoxWithScrollBar` instead of the default `irr::gui::IGUIEditBox`
- `GUIEditBoxWithScrollBar` allows to use a vertical scrollbar when it's needed
- `GUIEditBoxWithScrollBar` implements `irr::gui::IGUIEditBox`

2017-02-24 13:19 UTC, nerzhul requested changes

2017-02-24 13:19 UTC, nerzhul commented on build/android/jni/Android.mk
> +		jni/src/guieditboxwithscrollbar.cpp       \
please use same filename as other gui*.cpp files

2017-02-24 13:19 UTC, nerzhul commented on src/guieditboxwithscrollbar.h
> +	std::vector< core::stringw > m_broken_text;
no space in template types

2017-02-24 13:19 UTC, nerzhul commented on src/guieditboxwithscrollbar.cpp
> +			{
please fix the code style and place your braces on upper lines for conditions, switch & for

2017-02-24 13:19 UTC, nerzhul commented on src/guieditboxwithscrollbar.cpp
> +	if (event.KeyInput.Control)	{
missing space

2017-02-24 18:49 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +			e = new GUIEditBoxWithScrollBar(spec.fdefault.c_str(), true, Environment,this, spec.fid, rect, 20);
Tailing indents after `#endif`
Missing space after `true, Environment`

2017-02-24 19:10 UTC, Ekdohibs commented
Since this is a modification of irrlicht code, maybe it would be better to put it in the corresponding folder.

2017-03-07 09:06 UTC, nerzhul commented
Seems your merged instead of rebase, please do git rebase master

2017-03-07 10:01 UTC, closed without merging

2017-03-07 10:24 UTC, kilbith commented
New PR here : https://github.com/minetest/minetest/pull/5355