FormSpec : Add background color for textarea/field/pwdfield
minetest/minetest pull request #5361
Opened 2017-03-09 16:30 UTC by adelcoding1

Add new parameter value (background color) in FormSpec for textarea / field / pwdfield :

#### `pwdfield[<X>,<Y>;<W>,<H>;<name>;<label>;<bg_color>]`
* `bg_color` is the color of the background of the pwdfield

#### `field[<X>,<Y>;<W>,<H>;<name>;<label>;<default>;<bg_color>]`
* `bg_color` is the color of the background of the field

#### `field[<name>;<label>;<default>;<bg_color>]`
* As above, but without position/size units

#### `textarea[<X>,<Y>;<W>,<H>;<name>;<label>;<default>;<bg_color>]`
* Same as fields above, but with multi-line input

2017-03-10 08:50 UTC, nerzhul requested changes
Please fix code style issues

2017-03-10 08:50 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +		e = new GUIEditBoxWithScrollBar(0, true, Environment, this, spec.fid, rect, true, false);
please do affectation with variable declaration

2017-03-10 08:50 UTC, nerzhul commented on src/guiEditBoxWithScrollbar.cpp
> +			{
coding style issue

2017-03-10 08:50 UTC, nerzhul commented on src/guiEditBoxWithScrollbar.cpp
> +			{
code style issue

2017-03-10 09:02 UTC, rubenwardy commented
Adding new parameters to formspec tags causes backwards compatibility problems - and fields with background colors won't be visible on older clients

2017-03-10 15:22 UTC, kilbith commented
Someone should explain @adelcoding1 to make a protocol bump. He's very new to the MT's codebase.

2017-03-10 18:41 UTC, SmallJoker commented
@rubenwardy Please correct me if I'm overlooking something but this doesn't look like a required protocol bump to me. The old code splits the arguments and reads out all expected ones, the other indexes are just thrown away.
In case the server is running on an older version, this won't be a problem either because there are checks for ` parts.size() > 4 && ..`, which basically makes the background param optional.

2017-03-10 18:44 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +	{
`if (name == "") {`

2017-03-10 18:44 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +				e->drop();
Lower the whole block by one indent.

2017-03-13 15:10 UTC, kilbith commented
![screenshot_20170313_160853](https://cloud.githubusercontent.com/assets/7883281/23860549/92c33d24-0807-11e7-9962-76ee82fe61d8.png)

2017-03-18 12:06 UTC, nerzhul submitted a review, later dismissed

2017-03-18 12:06 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +			GUIEditBoxWithScrollBar * editbox_with_scrollbar =
no space before variable name

2017-09-30 09:48 UTC, kilbith commented
FYI, @adelcoding1 is my job mate and he's not going to rebase due to internal company politics.

2017-09-30 12:03 UTC, rubenwardy commented
This could potentially be merged now, due to the backwards compatibility change. There aren't any old versions the element can disappear on. I'll look into this at some point

2017-10-27 09:38 UTC, kilbith commented
Anyone to take care of this PR? It's a PITA to resolve merge conflicts from our fork...

2017-12-25 10:37 UTC, srifqi commented
So, basically this PR is approved and only need to be rebased?

2017-12-25 14:12 UTC, paramat commented
Not approved yet.

2019-03-15 20:27 UTC, closed without merging