[WIP] GUI: Convert loading screen's progress bar to image
minetest/minetest pull request #5362
Opened 2017-03-09 23:16 UTC by kilbith

This allows to have custom progress bars with images. Image scaling still need to be implemented.

![loadscreen](https://cloud.githubusercontent.com/assets/7883281/23774987/b3090c5a-0526-11e7-8a09-de7acdd03e03.gif)

2017-03-10 08:17 UTC, Zeno- commented
looks very nice!

2017-03-10 08:18 UTC, Zeno- commented on src/drawscene.cpp
> +		video::ITexture *progress_img = driver->getTexture(
Why is DIR_DELIM used above and not here?

2017-03-10 08:46 UTC, nerzhul requested changes
except the little thing okay for me

2017-03-10 08:46 UTC, nerzhul commented on src/drawscene.cpp
> +		const core::dimension2d<u32> img_size = progress_img_bg->getSize();
const ref instead of const

2017-03-10 10:38 UTC, kilbith commented
Updated with image scaling and hopefully ready for merge.

2017-03-10 10:42 UTC, nerzhul requested changes

2017-03-10 10:42 UTC, nerzhul commented on src/drawscene.cpp
> +		v2s32 img_pos((screensize.X / 2) - imgW / 2,
please factorize division operations mathematicly

2017-03-10 10:42 UTC, nerzhul commented on src/drawscene.cpp
>  	{
can you fix this brace please ?

2017-03-10 10:57 UTC, nerzhul approved these changes

2017-03-10 11:33 UTC, sfan5 approved these changes

2017-03-10 12:26 UTC, merged

2017-03-10 13:52 UTC, tobyplowy commented
@kilbith +1

2017-03-10 14:04 UTC, est31 commented
Nice change!

Who should be attributed as author of the textures in README?

2017-03-10 14:38 UTC, kilbith commented
@est31 Me, I made them in hurry. We'll have different textures in our engine.

2017-03-10 23:36 UTC, NathanSalapat commented
I assume this will not be possible to use on a server, as the server wouldn't send the image before anything starts loading?

2017-03-11 01:00 UTC, sofar commented
@NathanSalapat I assume not.

Can the images from texture packs override the default ones?

Can the images from subgames (for singleplayer games) override the default ones?

2017-03-11 02:47 UTC, kilbith commented
https://github.com/minetest/minetest/pull/5368