FormSpec: support custom size and spacing for slots in list
minetest/minetest pull request #5395
Opened 2017-03-14 12:51 UTC by adelcoding1

#### `list[<inventory location>;<list name>;<X>,<Y>;<W>,<H>;<starting item index>;<spacingW>,<spacingH>;<imgSize>]`
* Show an inventory list
* `spacingW` and `spacingH` are spacing factor sizes (relative to the slot) of a slot
  example : (1.0,1.0) for spacing means that there are no space between slots
* `imgSize` is the size factor (relative to the screen size) of a slot : a slot is always a square
  the default value for the `imgSize` is 0.0667 (40 pixels for a 800x600 screen size)
  the real size of `imgSize` in pixels is `imgSize * min(screenWidth, screenHeight)`

2017-03-21 14:59 UTC, nerzhul requested changes

2017-03-21 14:59 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +		std::vector<std::string> v_spacing_factors = has_spacing_factors ? split(parts[5], ',') : std::vector<std::string>();
line too long

2017-03-21 14:59 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
> +			_spacing.X = _imgsize.X + 2 * border + (s32)(stof(v_spacing_factors[0]) * (spacing.X - imgsize.X - 2 * border));
too long lines

2017-03-21 14:59 UTC, nerzhul commented on src/guiFormSpecMenu.cpp
>  			{
please fix this brace & the upper space

2017-03-22 08:32 UTC, kilbith commented on src/guiFormSpecMenu.cpp
> +			_spacing.X = _imgsize.X + 2 * border
Whitespace at end of line.

2017-03-22 08:33 UTC, kilbith commented on src/guiFormSpecMenu.cpp
> +		if (geom.X < 0 || geom.Y < 0 || start_i < 0
Whitespace at end of line.

2017-03-22 19:58 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +			+ (s32)(stof(v_spacing_factors[1]) * (spacing.Y - imgsize.Y - 2 * border));
One more indent for each continued new line. (may even require a 3rd line at the end)

2017-03-22 19:59 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +		if(has_startindex)
`if (has_startindex)` (space)

2017-03-22 20:00 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +			|| (has_spacing_factors && v_spacing_factors.size() != 2)) {
One more indent to seperate conditions from following instructions

2017-03-22 20:00 UTC, SmallJoker commented on src/guiFormSpecMenu.cpp
> +	for(u32 i = 0; i < m_inventorylists.size(); i++)
If already cleaning up the code style: `for (u32 ..)`

2017-03-23 10:05 UTC, nerzhul approved these changes

2017-03-23 10:05 UTC, nerzhul commented
Okay for me

2017-03-24 19:27 UTC, rubenwardy requested changes
This breaks backwards compatibility (due to the formspec version not being increased, and it also can't be increased nicely. The extra parameters won't be ignored on old clients, instead there will be an error and the list won't be shown). You need to do this instead by adding a new type called listoptions, unfortunately.

Or maybe it's worth putting common style things in a tag called style, for example foreground and background

2017-03-26 19:48 UTC, nerzhul commented
@rubenwardy maybe we should ignore the unknown tags like in HTML ?

2017-09-30 13:18 UTC, kilbith commented
https://github.com/minetest/minetest/pull/5361#issuecomment-333297488

2017-10-27 09:39 UTC, kilbith commented
Anyone for adoption please?

2017-12-23 03:08 UTC, paramat commented
The compatibility breakage is no issue now due to 0.5.

2019-06-10 00:23 UTC, closed without merging