Add Arm Inertia
minetest/minetest pull request #6050
Opened 2017-06-25 18:06 UTC by kilbith

Adresses https://github.com/minetest/minetest/issues/5174
Demo (outdated): https://www.youtube.com/watch?v=ls9vxBTr0hg

Optional feature, enabled by default. Wielding a pickaxe / sword gives the best effect.

2017-06-25 18:11 UTC, nerzhul requested changes

2017-06-25 18:11 UTC, nerzhul commented on src/camera.h
> +	float m_timer[2]        = {0.0f};
please init both offsets = { 0.0f, 0.0f }

2017-06-25 18:14 UTC, nerzhul approved these changes

2017-06-25 18:29 UTC, red-001 commented on src/camera.h
> +	float m_last_cam_pos[2] = { 0.0f, 0.0f };
Can you use `v2f`?

2017-06-25 19:04 UTC, nerzhul approved these changes

2017-06-25 19:59 UTC, sfan5 commented on builtin/settingtypes.txt
> +#    Arm inertia
longer description would be nice, something like
`more realistic movement of arm when turning view`

2017-06-25 20:13 UTC, paramat commented
:-1: Sorry this is unrealistic and belongs in a photo-realistic FPS.
Or at least disabled by default due to it's fanciness.
I thought you were not goimg to backport anything from your fork to to MT?

2017-06-25 20:42 UTC, nerzhul commented
it's more realistic than you outside dungeons which are ugly. This pr permits to have a nice game, unlike mapgen v7 and your outside dungeons.

2017-06-25 21:13 UTC, Fixer-007 commented
You can always make it configurable so mod or subgame can choose realistic or nonrealistic way.

2017-06-25 22:20 UTC, paramat commented
>  This pr permits to have a nice game, unlike mapgen v7 and your outside dungeons.

Mgv7 is much liked by many, and many like the protruding dungeons, but many do not also of course.

> also your stupidity is another time shown

Personal insult again, please stop.

> When do we refuse backports from forks ?

kilbith stated he would not backport from his fork, so i was wondering.

>  it's better than hidding bugs as features like you do.

It is an intentional feature.

2017-06-26 05:57 UTC, nerzhul requested changes
Hmmm i tested it and strangely when enabled i don't have any arm anymore

2017-06-26 07:35 UTC, kilbith commented
Please respect my PR and don't hijack it with drama and offtopic.

2017-06-26 07:42 UTC, celeron55 commented
Seems harmless and fine to me.

If players complain, it can be straightforwardly tweaked or removed.

2017-06-26 09:58 UTC, nerzhul commented on src/camera.cpp
> +	if (m_arm_inertia) {
is this possible to extract all code in this condition to a function please ?

2017-06-26 10:10 UTC, nerzhul approved these changes

2017-06-26 10:10 UTC, nerzhul commented
Strangely on a pure clean build it works (cmake workdir removed). If possible having a setting to manage the speed of the movement can be nice

2017-06-26 13:05 UTC, nerzhul commented on src/camera.cpp
> +void Camera::add_arm_inertia(const float &player_yaw, const f32 &frametime)
please pass float as value 4b < 8b (ref 64bits)

2017-06-26 14:32 UTC, bigfoot547 commented
> :-1: Sorry this is **unrealistic** and i feel it belongs in a **photo-realistic** FPS.

Or maybe a photo-_un_-realistic FPS. :wink:

2017-06-26 17:14 UTC, SmallJoker commented
I just tested the patch and it looks very nice. The only thing I could complain is the abrupt stop when the item got back on place, but it looks good even without an extra smooth or wiggle effect there. KISS. :+1: once the comment is handled.

2017-06-26 17:15 UTC, SmallJoker commented on src/camera.cpp
> +void Camera::add_arm_inertia(f32 player_yaw, f32 frametime)
`addArmInertia` to follow our function naming rules

2017-06-26 18:03 UTC, merged

2017-06-28 18:05 UTC, paramat commented
Removed my -1. I've been watching MC videos and noticed that with a moderate displacement, smooth motion and fast return it doesn't look bad.
I was having a day of arguments as you know and that affected my reaction to this PR, sorry for that.