Set visibility of players/hide them from others
minetest/minetest pull request #9863
Opened 2020-05-14 20:22 UTC by Lejo1

Rebase of #8397

When players visibility is = false he's not show as object, in get_player_names or in the /status info

2020-06-23 23:08 UTC, rubenwardy commented on src/script/lua_api/l_object.cpp
> +	return 1;
useless and undocumented return value

2020-06-24 08:57 UTC, Lejo1 commented on src/script/lua_api/l_object.cpp
> +	return 1;
Removed

2020-10-19 20:04 UTC, Zughy requested changes
Really nice (and needed) feature, bumpbump

2020-10-19 20:04 UTC, Zughy commented on src/script/lua_api/l_object.cpp
> +}
Same as before
```
        NO_MAP_LOCK_REQUIRED;
	ObjectRef *ref = checkobject(L, 1);
	ServerActiveObject *sao = getobject(ref);
	if (sao == nullptr)
		return 0;

	lua_pushboolean(L, sao->getVisible());
	return 1;
```
(or `!sao`)

2020-10-19 20:34 UTC, Lejo1 commented on src/script/lua_api/l_object.cpp
> +	return 1;
Thanks, will just do that than!

2020-10-21 20:30 UTC, rubenwardy reviewed
There's already an object property called [`is_visible`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6829), this would be confusing to modders. 

This could be changed to use that object property, except that:

* is_visible=false objects are still collidable
* children of invisible objects may be visible

Perhaps this should be renamed to `set_hidden()` or `set_enabled()`. Android has a ternary for this - `visible`, `invisible`, `gone`.

2020-10-21 20:30 UTC, rubenwardy commented on src/clientiface.cpp
> +	if (in_game) {
```c++
NetworkPacket notice(TOCLIENT_UPDATE_PLAYER_LIST, 0,
	PEER_ID_INEXISTENT);
notice << (u8) (in_game ? PLAYER_LIST_ADD : PLAYER_LIST_REMOVE)
		<< (u16) 1 << player_name;
sendToAll(&notice);

UpdatePlayerList();
```

2020-10-22 12:26 UTC, Lejo1 commented on src/clientiface.cpp
> +	if (in_game) {
Thanks, added!

2020-10-22 12:27 UTC, Lejo1 commented on src/script/lua_api/l_object.cpp
> +	return 1;
changed.

2020-10-22 12:27 UTC, Lejo1 commented on src/script/lua_api/l_object.cpp
> +}
changed.

2020-10-22 12:28 UTC, Lejo1 commented
Used set_player_hidden as it's pretty different to the object is_visible one.

2020-10-22 13:00 UTC, Zughy commented on src/script/lua_api/l_object.cpp
> +	return 1;
I meant empty lines too. To follow the order `check` -> `variables declaration` -> `execution+return`

2020-10-23 06:42 UTC, Lejo1 commented on src/script/lua_api/l_object.cpp
> +	return 1;
oh, right changed again

2021-03-04 16:30 UTC, Lejo1 commented
Rebased

2021-10-15 08:49 UTC, AFCMS commented
@Lejo1 Can the player still be seen by using hack clients? In other words, can this pr fully solve #11693 ?

2021-10-15 11:06 UTC, Lejo1 commented
It fully hides the client even by hack clients, but also as you said fakes the get_player_names entry.

2022-04-30 22:40 UTC, Zughy commented
@Lejo1 it should be rebased again, sorry..

2022-05-04 19:44 UTC, Lejo1 commented
Rebased.

2022-09-25 18:53 UTC, SmallJoker commented
https://irc.minetest.net/minetest-dev/2022-09-25#i_6018734

 A few notes, mainly inputs from my side:

 * The PR does too much. Let mods implement chat messages (status, join/leave) for hidden players, if that's wanted
 * Hidden player's attachments must not be sent to other players or they likely stack at (0,0,0) due to unknown parent.
 * What about attached sounds / particlespawners ?

Quick & dirty implementation idea without needing this PR:

 * Set the player's texture to a transparent pixel (blank.png ?)
 * `pointable = false` object property

My implementation idea:

 * Extend `is_visible` on players to hide the player mesh
 * Hide  attachments for `is_visible` parents (fake removal & re-add could get rather messy)
 * Let mods deal with the rest

2022-09-25 19:10 UTC, closed without merging